export const leafletBasic = ''
export const leafletMarkerCirclePolygon = ''
export const leafletPopup = ''
export const leafletGeoJSON = ''
export const leafletLayerGroup = ''
export const leafletCustomIcon = ''
