import type { ThemeDefinition } from 'vuetify'

export const staticPrimaryColor = '#8146ff'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'secondary': '#8A8D93',
      'on-secondary': '#fff',
      'success': '#56CA00',
      'on-success': '#fff',
      'info': '#16B1FF',
      'warning': '#FFB400',
      'on-warning': '#fff',
      'error': '#FF4C51',
      'background': '#F4F5FA',
      'on-background': '#3A3541',
      'surface': '#FFFFFF',
      'on-surface': '#3A3541',
      'grey-50': '#FAFAFA',
      'grey-100': '#F5F5F5',
      'grey-200': '#EEEEEE',
      'grey-300': '#E0E0E0',
      'grey-400': '#BDBDBD',
      'grey-500': '#9E9E9E',
      'grey-600': '#757575',
      'grey-700': '#616161',
      'grey-800': '#424242',
      'grey-900': '#212121',
      'perfect-scrollbar-thumb': '#DBDADE',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
    },

    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#3A3541',
      'overlay-scrim-opacity': 0.5,
      'tooltip-background': '#1A0E33',
      'hover-opacity': 0.04,
      'activated-opacity': 0.54,
      'focus-opacity': 0.12,
      'selected-opacity': 0.08,
      'disabled-opacity': 0.38,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'divider-opacity': 0.12,
      'border-color': '#3A3541',
      'border-opacity': 0.23,

      // Shadows
      'shadow-key-umbra-opacity': 'rgba(var(--v-theme-on-surface), 0.08)',
      'shadow-key-penumbra-opacity': 'rgba(var(--v-theme-on-surface), 0.12)',
      'shadow-key-ambient-opacity': 'rgba(var(--v-theme-on-surface), 0.04)',
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'secondary': '#8A8D93',
      'on-secondary': '#fff',
      'success': '#56CA00',
      'on-success': '#fff',
      'info': '#16B1FF',
      'on-info': '#fff',
      'warning': '#FFB400',
      'on-warning': '#fff',
      'error': '#FF4C51',
      'on-error': '#fff',
      'background': '#28243D',
      'on-background': '#E7E3FC',
      'surface': '#312D4B',
      'on-surface': '#E7E3FC',
      'grey-50': '#2A2E42',
      'grey-100': '#2F3349',
      'grey-200': '#4A5072',
      'grey-300': '#5E6692',
      'grey-400': '#7983BB',
      'grey-500': '#8692D0',
      'grey-600': '#AAB3DE',
      'grey-700': '#B6BEE3',
      'grey-800': '#CFD3EC',
      'grey-900': '#E7E9F6',
      'perfect-scrollbar-thumb': '#4A5072',
      'skin-bordered-background': '#312d4b',
      'skin-bordered-surface': '#312d4b',
    },
    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#3A3541',
      'overlay-scrim-opacity': 0.5,
      'tooltip-background': '#F7F4FF',
      'hover-opacity': 0.04,
      'focus-opacity': 0.12,
      'selected-opacity': 0.08,
      'activated-opacity': 0.54,
      'disabled-opacity': 0.38,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'divider-opacity': 0.12,
      'border-color': '#E7E3FC',
      'border-opacity': 0.23,

      // Shadows
      'shadow-key-umbra-opacity': 'rgba(20, 18, 33, 0.08)',
      'shadow-key-penumbra-opacity': 'rgba(20, 18, 33, 0.12)',
      'shadow-key-ambient-opacity': 'rgba(20, 18, 33, 0.04)',
    },
  },
}

export default themes
