import type { ThemeDefinition } from 'vuetify'

export const staticPrimaryColor = '#8C57FF'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'secondary': '#8A8D93',
      'on-secondary': '#fff',
      'success': '#56CA00',
      'on-success': '#fff',
      'info': '#16B1FF',
      'on-info': '#fff',
      'warning': '#FFB400',
      'on-warning': '#fff',
      'error': '#FF4C51',
      'on-error': '#fff',
      'background': '#f4f5fa',
      'on-background': '#2E263D',
      'surface': '#fff',
      'on-surface': '#2E263D',
      'grey-50': '#FAFAFA',
      'grey-100': '#F5F5F5',
      'grey-200': '#EEEEEE',
      'grey-300': '#E0E0E0',
      'grey-400': '#BDBDBD',
      'grey-500': '#9E9E9E',
      'grey-600': '#757575',
      'grey-700': '#616161',
      'grey-800': '#424242',
      'grey-900': '#212121',
      'perfect-scrollbar-thumb': '#F0F2F8',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#fafafa',
    },

    variables: {
      'primary-dark': '#7E4EE6',
      'primary-light': '#A379FF',
      'secondary-dark': '#7C7F84',
      'secondary-light': '#A1A4A9',
      'success-dark': '#4DB600',
      'success-light': '#78D533',
      'info-dark': '#149FE6',
      'info-light': '#45C1FF',
      'warning-dark': '#E6A200',
      'warning-light': '#FFC333',
      'error-dark': '#E64449',
      'error-light': '#FF7074',
      'code-color': '#d400ff',
      'overlay-scrim-background': '#2E263D',
      'tooltip-background': '#1A0E33',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.08,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#2E263D',
      'border-opacity': 0.12,
      'table-header-color': '#F6F7FB',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,

      // 👉 shadows
      'shadow-key-umbra-color': '#2E263D',
    },
  },

  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'secondary': '#8A8D93',
      'on-secondary': '#fff',
      'success': '#56CA00',
      'on-success': '#fff',
      'info': '#16B1FF',
      'on-info': '#fff',
      'warning': '#FFB400',
      'on-warning': '#fff',
      'error': '#FF4C51',
      'on-error': '#fff',
      'background': '#28243D',
      'on-background': '#E7E3FC',
      'surface': '#312d4b',
      'on-surface': '#E7E3FC',
      'grey-50': '#2A2E42',
      'grey-100': '#2F3349',
      'grey-200': '#4A5072',
      'grey-300': '#5E6692',
      'grey-400': '#7983BB',
      'grey-500': '#8692D0',
      'grey-600': '#AAB3DE',
      'grey-700': '#B6BEE3',
      'grey-800': '#CFD3EC',
      'grey-900': '#E7E9F6',
      'perfect-scrollbar-thumb': '#474360',
      'skin-bordered-background': '#312d4b',
      'skin-bordered-surface': '#312d4b',
      'expansion-panel-text-custom-bg': '#373350',
    },

    variables: {
      'primary-dark': '#7E4EE6',
      'primary-light': '#A379FF',
      'secondary-dark': '#7C7F84',
      'secondary-light': '#A1A4A9',
      'success-dark': '#4DB600',
      'success-light': '#78D533',
      'info-dark': '#149FE6',
      'info-light': '#45C1FF',
      'warning-dark': '#E6A200',
      'warning-light': '#FFC333',
      'error-dark': '#E64449',
      'error-light': '#FF7074',
      'code-color': '#d400ff',
      'overlay-scrim-background': '#312D4B',
      'tooltip-background': '#F7F4FF',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.08,
      'pressed-opacity': 0.14,
      'disabled-opacity': 0.4,
      'dragged-opacity': 0.1,
      'border-color': '#E7E3FC',
      'border-opacity': 0.12,
      'table-header-color': '#3D3759',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,

      // 👉 Shadows
      'shadow-key-umbra-color': '#131120',
    },
  },
}

export default themes
