import './app-bar-search'
import './apps/user-list'
import './jwt'
import './pages/datatable'
import './pages/faq'
import './pages/help-center'
import './pages/profile'

// Apps
import './apps/academy'
import './apps/calendar'
import './apps/chat'
import './apps/ecommerce'
import './apps/email'
import './apps/invoice'
import './apps/permissions'
