// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppCardActions: typeof import('./src/@core/components/AppCardActions.vue')['default']
    AppCardCode: typeof import('./src/@core/components/AppCardCode.vue')['default']
    Customizer: typeof import('./src/@core/components/Customizer.vue')['default']
    CustomizerSection: typeof import('./src/@core/components/CustomizerSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCustomizer: typeof import('./src/components/TheCustomizer.vue')['default']
  }
}

export {}
