export const monthPickerBasic = ''
export const monthPickerAllowedMonths = ''
export const monthPickerIcons = ''
export const monthPickerMultiple = ''
export const monthPickerReadonlyAndDisabled = ''
export const monthPickerWidth = ''
export const monthPickerDialogAndMenu = ''
