<template>
  <div class="demo-space-x">
    <v-btn
      variant="outlined"
      color="primary"
    >
      Primary
    </v-btn>
    <v-btn
      variant="outlined"
      color="secondary"
    >
      Secondary
    </v-btn>
    <v-btn
      variant="outlined"
      color="success"
    >
      Success
    </v-btn>
    <v-btn
      variant="outlined"
      color="info"
    >
      Info
    </v-btn>
    <v-btn
      variant="outlined"
      color="warning"
    >
      Warning
    </v-btn>
    <v-btn
      variant="outlined"
      color="error"
    >
      Error
    </v-btn>
  </div>
</template>
