export const menuBasic = ''
export const menuPosition = ''
export const menuCloseOn = ''
export const menuDisabled = ''
export const menuHover = ''
export const menuTooltip = ''
export const menuTransitions = ''
export const menuPopover = ''
