<template>
  <div class="demo-space-x">
    <VAvatar
      rounded="0"
      color="primary"
    >
      <VIcon
        color="white"
        size="25"
        icon="mdi-account-outline"
      />
    </VAvatar>

    <VAvatar
      rounded="0"
      color="secondary"
    >
      <VIcon
        color="white"
        size="25"
        icon="mdi-account-outline"
      />
    </VAvatar>

    <VAvatar
      rounded="0"
      color="success"
    >
      <VIcon
        color="white"
        size="25"
        icon="mdi-account-outline"
      />
    </VAvatar>

    <VAvatar
      rounded="0"
      color="info"
    >
      <VIcon
        color="white"
        size="25"
        icon="mdi-account-outline"
      />
    </VAvatar>

    <VAvatar
      rounded="0"
      color="warning"
    >
      <VIcon
        color="white"
        size="25"
        icon="mdi-account-outline"
      />
    </VAvatar>

    <VAvatar
      rounded="0"
      color="error"
    >
      <VIcon
        color="white"
        size="25"
        icon="mdi-account-outline"
      />
    </VAvatar>
  </div>
</template>
