import type { EcommerceProduct } from '../types'
import mock from '@/@fake-db/mock'
import { paginateArray } from '@/@fake-db/utils'

import product1 from '@images/ecommerce-images/product-1.png'
import product10 from '@images/ecommerce-images/product-10.png'
import product11 from '@images/ecommerce-images/product-11.png'
import product12 from '@images/ecommerce-images/product-12.png'
import product13 from '@images/ecommerce-images/product-13.png'
import product14 from '@images/ecommerce-images/product-14.png'
import product15 from '@images/ecommerce-images/product-15.png'
import product16 from '@images/ecommerce-images/product-16.png'
import product17 from '@images/ecommerce-images/product-17.png'
import product18 from '@images/ecommerce-images/product-18.png'
import product19 from '@images/ecommerce-images/product-19.png'
import product2 from '@images/ecommerce-images/product-2.png'
import product20 from '@images/ecommerce-images/product-20.png'
import product3 from '@images/ecommerce-images/product-3.png'
import product4 from '@images/ecommerce-images/product-4.png'
import product5 from '@images/ecommerce-images/product-5.png'
import product6 from '@images/ecommerce-images/product-6.png'
import product7 from '@images/ecommerce-images/product-7.png'
import product8 from '@images/ecommerce-images/product-8.png'
import product9 from '@images/ecommerce-images/product-9.png'

const database: EcommerceProduct[] = [
  {
    id: 1,
    product_name: 'iPhone 14 Pro',
    category: 2,
    stock: true,
    sku: 19472,
    price: '$999',
    qty: 665,
    status: 3,
    image: product1,
    product_brand: 'Super Retina XDR display footnote Pro Motion technology',
  },
  {
    id: 2,
    product_name: 'Echo Dot (4th Gen)',
    category: 2,
    stock: false,
    sku: 72836,
    price: '$25.50',
    qty: 827,
    status: 2,
    image: product2,
    product_brand: 'Echo Dot Smart speaker with Alexa',
  },
  {
    id: 3,
    product_name: 'Dohioue Wall Clock',
    category: 0,
    stock: false,
    sku: 29540,
    price: '$16.34',
    qty: 804,
    status: 2,
    image: product3,
    product_brand: 'Modern 10 Inch Battery Operated Wall Clocks',
  },
  {
    id: 4,
    product_name: 'INZCOU Running Shoes',
    category: 3,
    stock: false,
    sku: 49402,
    price: '$36.98',
    qty: 528,
    status: 1,
    image: product4,
    product_brand: 'Lightweight Tennis Shoes Non Slip Gym Workout Shoes',
  },
  {
    id: 5,
    product_name: 'Apple Watch Series 7',
    category: 4,
    stock: false,
    sku: 46658,
    price: '$799',
    qty: 851,
    status: 1,
    image: product5,
    product_brand: 'Starlight Aluminum Case with Starlight Sport Band.',
  },
  {
    id: 6,
    product_name: 'Meta Quest 2',
    category: 4,
    stock: true,
    sku: 57640,
    price: '$299',
    qty: 962,
    status: 1,
    image: product6,
    product_brand: 'Advanced All-In-One Virtual Reality Headset',
  },
  {
    id: 7,
    product_name: 'MacBook Pro 16',
    category: 2,
    stock: true,
    sku: 92885,
    price: '$2648.95',
    qty: 965,
    status: 2,
    image: product7,
    product_brand: 'Laptop M2 Pro chip with 12‑core CPU and 19‑core GPU',
  },
  {
    id: 8,
    product_name: 'SAMSUNG Galaxy S22 Ultra',
    category: 2,
    stock: true,
    sku: 75257,
    price: '$899',
    qty: 447,
    status: 2,
    image: product8,
    product_brand: 'Android Smartphone, 256GB, 8K Camera',
  },
  {
    id: 9,
    product_name: 'Air Jordan',
    category: 3,
    stock: false,
    sku: 31063,
    price: '$125',
    qty: 942,
    status: 3,
    image: product9,
    product_brand: 'Air Jordan is a line of basketball shoes produced by Nike',
  },
  {
    id: 10,
    product_name: 'VISKABACKA',
    category: 1,
    stock: false,
    sku: 91848,
    price: '$190.45',
    qty: 133,
    status: 1,
    image: product10,
    product_brand: 'Armchair, Skartofta black/light grey',
  },
  {
    id: 11,
    product_name: 'Nintendo Switch',
    category: 5,
    stock: true,
    sku: 52575,
    price: '$296.99',
    qty: 870,
    status: 3,
    image: product11,
    product_brand: 'TV Mode, Tabletop Mode, Handheld Mode',
  },
  {
    id: 12,
    product_name: 'PlayStation 5',
    category: 5,
    stock: true,
    sku: 59551,
    price: '$499',
    qty: 145,
    status: 1,
    image: product12,
    product_brand: 'Marvel at incredible graphics and experience',
  },
  {
    id: 13,
    product_name: 'Amazon Fire TV',
    category: 2,
    stock: false,
    sku: 5829,
    price: '$263.49',
    qty: 587,
    status: 1,
    image: product13,
    product_brand: '4K UHD smart TV, stream live TV without cable',
  },
  {
    id: 14,
    product_name: 'Smiletag Ceramic Vase',
    category: 1,
    stock: false,
    sku: 24456,
    price: '$34.99',
    qty: 310,
    status: 1,
    image: product14,
    product_brand: 'Modern Farmhouse Decor Vase Set of 3',
  },
  {
    id: 15,
    product_name: 'Apple iPad',
    category: 2,
    stock: true,
    sku: 35946,
    price: '$248.39',
    qty: 468,
    status: 2,
    image: product15,
    product_brand: '10.2-inch Retina Display, 64GB',
  },
  {
    id: 16,
    product_name: 'BANGE Anti Theft Backpack',
    category: 4,
    stock: true,
    sku: 41867,
    price: '$79.99',
    qty: 519,
    status: 3,
    image: product16,
    product_brand: 'Smart Business Laptop Fits 15.6 Inch Notebook',
  },
  {
    id: 17,
    product_name: 'Xbox Series X/S',
    category: 5,
    stock: true,
    sku: 43224,
    price: '$49.99',
    qty: 787,
    status: 2,
    image: product17,
    product_brand: 'Dual Controller Charger Station Dock',
  },
  {
    id: 18,
    product_name: 'Canon EOS Rebel T7',
    category: 2,
    stock: true,
    sku: 63474,
    price: '$399',
    qty: 810,
    status: 1,
    image: product18,
    product_brand: '18-55mm Lens | Built-in Wi-Fi | 24.1 MP CMOS Sensor',
  },
  {
    id: 19,
    product_name: 'Honiway Wall Mirror',
    category: 1,
    stock: false,
    sku: 15859,
    price: '$23.99',
    qty: 735,
    status: 3,
    image: product19,
    product_brand: 'Decorative 12 inch Rustic Wood Mirror Sunburst Boho',
  },
  {
    id: 20,
    product_name: 'Tommaso Veloce Shoes',
    category: 3,
    stock: false,
    sku: 28844,
    price: '$922.09',
    qty: 294,
    status: 3,
    image: product20,
    product_brand: 'Peloton Shoes Triathlon Road Bike Indoor Cycling',
  },
  {
    id: 21,
    product_name: 'Zoolab',
    category: 0,
    stock: true,
    sku: 99009,
    price: '$719.13',
    qty: 927,
    status: 1,
    image: product1,
    product_brand: 'Cruickshank-Jones',
  },
  {
    id: 22,
    product_name: 'Viva',
    category: 1,
    stock: false,
    sku: 53795,
    price: '$775.80',
    qty: 442,
    status: 1,
    image: product2,
    product_brand: 'Ferry Group',
  },
  {
    id: 23,
    product_name: 'Transcof',
    category: 3,
    stock: true,
    sku: 77663,
    price: '$817.60',
    qty: 256,
    status: 2,
    image: product3,
    product_brand: 'Bruen-Heathcote',
  },
  {
    id: 24,
    product_name: 'Uerified',
    category: 0,
    stock: false,
    sku: 45282,
    price: '$167.19',
    qty: 728,
    status: 2,
    image: product4,
    product_brand: 'Koch Group',
  },
  {
    id: 25,
    product_name: 'Y-find',
    category: 1,
    stock: false,
    sku: 5622,
    price: '$189.77',
    qty: 445,
    status: 1,
    image: product5,
    product_brand: 'Emmerich and Sons',
  },
  {
    id: 26,
    product_name: 'Wigtax',
    category: 0,
    stock: true,
    sku: 38920,
    price: '$411.46',
    qty: 857,
    status: 1,
    image: product6,
    product_brand: 'Zulauf-Prohaska',
  },
  {
    id: 27,
    product_name: 'Tempsoft',
    category: 0,
    stock: true,
    sku: 78211,
    price: '$961.76',
    qty: 975,
    status: 2,
    image: product7,
    product_brand: 'VonRueden, Rogahn and Kris',
  },
  {
    id: 28,
    product_name: 'Rt',
    category: 0,
    stock: true,
    sku: 98552,
    price: '$514.14',
    qty: 39,
    status: 2,
    image: product8,
    product_brand: 'Romaguera, O\'Connell and Abernathy',
  },
  {
    id: 29,
    product_name: 'Zontrax',
    category: 3,
    stock: true,
    sku: 7151,
    price: '$591.30',
    qty: 74,
    status: 2,
    image: product9,
    product_brand: 'Mills, Hagenes and Bednar',
  },
  {
    id: 30,
    product_name: 'Keylex',
    category: 0,
    stock: true,
    sku: 79571,
    price: '$928.07',
    qty: 245,
    status: 3,
    image: product10,
    product_brand: 'Sanford, Harvey and Parisian',
  },
  {
    id: 31,
    product_name: 'Trippledex',
    category: 1,
    stock: false,
    sku: 51597,
    price: '$312.03',
    qty: 657,
    status: 3,
    image: product11,
    product_brand: 'Conroy-Bergstrom',
  },
  {
    id: 32,
    product_name: 'Opela',
    category: 0,
    stock: true,
    sku: 6506,
    price: '$951.29',
    qty: 770,
    status: 2,
    image: product12,
    product_brand: 'Langosh Inc',
  },
  {
    id: 33,
    product_name: 'Span',
    category: 3,
    stock: false,
    sku: 33523,
    price: '$600.43',
    qty: 622,
    status: 3,
    image: product13,
    product_brand: 'Jerde-Walsh',
  },
  {
    id: 34,
    product_name: 'Rank',
    category: 0,
    stock: false,
    sku: 60307,
    price: '$337.90',
    qty: 896,
    status: 1,
    image: product14,
    product_brand: 'Barrows, Quitzon and Roberts',
  },
  {
    id: 35,
    product_name: 'Tempsoft',
    category: 0,
    stock: true,
    sku: 75059,
    price: '$959.47',
    qty: 239,
    status: 3,
    image: product15,
    product_brand: 'Russel-Grant',
  },
  {
    id: 36,
    product_name: 'Ventosanzap',
    category: 0,
    stock: true,
    sku: 69072,
    price: '$756.81',
    qty: 410,
    status: 1,
    image: product16,
    product_brand: 'O\'Conner-Zboncak',
  },
  {
    id: 37,
    product_name: 'Mat Lam Tam',
    category: 0,
    stock: false,
    sku: 68290,
    price: '$256.86',
    qty: 630,
    status: 2,
    image: product17,
    product_brand: 'Rutherford, Heller and Bashirian',
  },
  {
    id: 38,
    product_name: 'Zamit',
    category: 3,
    stock: true,
    sku: 89552,
    price: '$378.54',
    qty: 247,
    status: 3,
    image: product18,
    product_brand: 'Swift-Altenwerth',
  },
  {
    id: 39,
    product_name: 'Tresom',
    category: 3,
    stock: true,
    sku: 50863,
    price: '$166.17',
    qty: 672,
    status: 3,
    image: product19,
    product_brand: 'O\'Kon, Waelchi and Lesch',
  },
  {
    id: 40,
    product_name: 'Viva',
    category: 0,
    stock: false,
    sku: 90484,
    price: '$745.76',
    qty: 697,
    status: 2,
    image: product20,
    product_brand: 'Johnston, Anderson and Metz',
  },
  {
    id: 41,
    product_name: 'Matsoft',
    category: 0,
    stock: true,
    sku: 76980,
    price: '$603.16',
    qty: 74,
    status: 2,
    image: product1,
    product_brand: 'O\'Conner, Paucek and Braun',
  },
  {
    id: 42,
    product_name: 'Wiodex',
    category: 1,
    stock: true,
    sku: 66971,
    price: '$772.51',
    qty: 280,
    status: 2,
    image: product2,
    product_brand: 'Wisoky-Kassulke',
  },
  {
    id: 43,
    product_name: 'Keylex',
    category: 3,
    stock: false,
    sku: 16589,
    price: '$986.22',
    qty: 758,
    status: 3,
    image: product3,
    product_brand: 'Haag, Bruen and Reichel',
  },
  {
    id: 44,
    product_name: 'Konklux',
    category: 0,
    stock: true,
    sku: 73896,
    price: '$988.47',
    qty: 14,
    status: 3,
    image: product4,
    product_brand: 'Ankunding Inc',
  },
  {
    id: 45,
    product_name: 'Tresom',
    category: 0,
    stock: false,
    sku: 67489,
    price: '$946.62',
    qty: 35,
    status: 3,
    image: product5,
    product_brand: 'Deckow and Sons',
  },
  {
    id: 46,
    product_name: 'Quo Lux',
    category: 3,
    stock: true,
    sku: 48177,
    price: '$224.28',
    qty: 935,
    status: 1,
    image: product1,
    product_brand: 'Kreiger, Reynolds and Sporer',
  },
  {
    id: 47,
    product_name: 'Roldlamis',
    category: 1,
    stock: true,
    sku: 225,
    price: '$952.14',
    qty: 361,
    status: 2,
    image: product6,
    product_brand: 'Kuphal-Abbott',
  },
  {
    id: 48,
    product_name: 'Tampflex',
    category: 0,
    stock: false,
    sku: 29438,
    price: '$646.21',
    qty: 908,
    status: 1,
    image: product7,
    product_brand: 'Romaguera, Schmeler and Volkman',
  },
  {
    id: 49,
    product_name: 'Span',
    category: 1,
    stock: true,
    sku: 55666,
    price: '$583.13',
    qty: 898,
    status: 1,
    image: product8,
    product_brand: 'Hane-Romaguera',
  },
  {
    id: 50,
    product_name: 'Zamit',
    category: 0,
    stock: false,
    sku: 55860,
    price: '$273.67',
    qty: 332,
    status: 2,
    image: product9,
    product_brand: 'Hoeger-Powlowski',
  },
  {
    id: 51,
    product_name: 'Witchip',
    category: 1,
    stock: false,
    sku: 41156,
    price: '$573.24',
    qty: 55,
    status: 3,
    image: product10,
    product_brand: 'Heidenreich, Keeling and Kuhn',
  },
  {
    id: 52,
    product_name: 'Ratity',
    category: 3,
    stock: true,
    sku: 8147,
    price: '$571.76',
    qty: 839,
    status: 2,
    image: product11,
    product_brand: 'Beier and Sons',
  },
  {
    id: 53,
    product_name: 'Voltsillam',
    category: 1,
    stock: true,
    sku: 78814,
    price: '$396.79',
    qty: 496,
    status: 2,
    image: product12,
    product_brand: 'Jones and Sons',
  },
  {
    id: 54,
    product_name: 'Voltsillam',
    category: 3,
    stock: false,
    sku: 96040,
    price: '$140.79',
    qty: 50,
    status: 1,
    image: product13,
    product_brand: 'Mohr and Sons',
  },
  {
    id: 55,
    product_name: 'Matsoft',
    category: 0,
    stock: true,
    sku: 99482,
    price: '$723.01',
    qty: 453,
    status: 1,
    image: product1,
    product_brand: 'Kling-Hayes',
  },
  {
    id: 56,
    product_name: 'Rt',
    category: 0,
    stock: true,
    sku: 56480,
    price: '$849.72',
    qty: 293,
    status: 3,
    image: product14,
    product_brand: 'Brekke-Lubowitz',
  },
  {
    id: 57,
    product_name: 'Konklab',
    category: 0,
    stock: true,
    sku: 95499,
    price: '$152.02',
    qty: 263,
    status: 2,
    image: product15,
    product_brand: 'Kiehn LLC',
  },
  {
    id: 58,
    product_name: 'Lotstring',
    category: 0,
    stock: false,
    sku: 83893,
    price: '$111.29',
    qty: 231,
    status: 3,
    image: product16,
    product_brand: 'Windler-Corwin',
  },
  {
    id: 59,
    product_name: 'Keylex',
    category: 3,
    stock: true,
    sku: 24943,
    price: '$148.67',
    qty: 289,
    status: 3,
    image: product17,
    product_brand: 'Reynolds, Buckridge and Schmeler',
  },
  {
    id: 60,
    product_name: 'Transcof',
    category: 0,
    stock: false,
    sku: 92258,
    price: '$369.54',
    qty: 268,
    status: 1,
    image: product18,
    product_brand: 'Jacobs-Farrell',
  },
  {
    id: 61,
    product_name: 'Opela',
    category: 0,
    stock: true,
    sku: 15281,
    price: '$890.33',
    qty: 115,
    status: 2,
    image: product19,
    product_brand: 'Beier-Bergstrom',
  },
  {
    id: 62,
    product_name: 'Rlowdesk',
    category: 0,
    stock: false,
    sku: 92346,
    price: '$668.81',
    qty: 850,
    status: 1,
    image: product20,
    product_brand: 'Roob and Sons',
  },
  {
    id: 63,
    product_name: 'Kanlam',
    category: 0,
    stock: false,
    sku: 8590,
    price: '$407.46',
    qty: 547,
    status: 3,
    image: product2,
    product_brand: 'Hauck Group',
  },
  {
    id: 64,
    product_name: 'Rembucket',
    category: 0,
    stock: false,
    sku: 57694,
    price: '$763.28',
    qty: 188,
    status: 1,
    image: product2,
    product_brand: 'Reynolds-Lindgren',
  },
  {
    id: 65,
    product_name: 'Tin',
    category: 0,
    stock: false,
    sku: 83532,
    price: '$866.51',
    qty: 469,
    status: 3,
    image: product2,
    product_brand: 'Stroman and Sons',
  },
  {
    id: 66,
    product_name: 'Trippledex',
    category: 0,
    stock: false,
    sku: 85878,
    price: '$390.28',
    qty: 753,
    status: 2,
    image: product2,
    product_brand: 'Kihn-Wisoky',
  },
  {
    id: 67,
    product_name: 'Redhold',
    category: 0,
    stock: false,
    sku: 18810,
    price: '$944.68',
    qty: 783,
    status: 3,
    image: product2,
    product_brand: 'Konopelski-Hauck',
  },
  {
    id: 68,
    product_name: 'Pannier',
    category: 3,
    stock: false,
    sku: 42375,
    price: '$802.49',
    qty: 371,
    status: 1,
    image: product3,
    product_brand: 'Rau Inc',
  },
  {
    id: 69,
    product_name: 'Rlexidy',
    category: 0,
    stock: true,
    sku: 55165,
    price: '$812.75',
    qty: 981,
    status: 3,
    image: product3,
    product_brand: 'Torp-Lebsack',
  },
  {
    id: 70,
    product_name: 'Keylex',
    category: 1,
    stock: false,
    sku: 92443,
    price: '$338.64',
    qty: 44,
    status: 1,
    image: product3,
    product_brand: 'Hane-Bednar',
  },
  {
    id: 71,
    product_name: 'Kuobam',
    category: 0,
    stock: false,
    sku: 98203,
    price: '$190.82',
    qty: 212,
    status: 1,
    image: product3,
    product_brand: 'Rice Group',
  },
  {
    id: 72,
    product_name: 'Ulphazap',
    category: 1,
    stock: false,
    sku: 49451,
    price: '$658.79',
    qty: 707,
    status: 3,
    image: product3,
    product_brand: 'West, White and Rau',
  },
  {
    id: 73,
    product_name: 'Wiodex',
    category: 0,
    stock: true,
    sku: 48644,
    price: '$231.38',
    qty: 513,
    status: 3,
    image: product4,
    product_brand: 'Keeling-Dicki',
  },
  {
    id: 74,
    product_name: 'Veribet',
    category: 0,
    stock: true,
    sku: 86347,
    price: '$885.15',
    qty: 953,
    status: 2,
    image: product4,
    product_brand: 'Gerlach, Bernhard and Schmidt',
  },
  {
    id: 75,
    product_name: 'Rix San',
    category: 0,
    stock: true,
    sku: 53970,
    price: '$897.45',
    qty: 305,
    status: 3,
    image: product4,
    product_brand: 'Emmerich, Hills and Beer',
  },
  {
    id: 76,
    product_name: 'Zoolab',
    category: 0,
    stock: false,
    sku: 64602,
    price: '$753.84',
    qty: 269,
    status: 1,
    image: product4,
    product_brand: 'Treutel-Dickinson',
  },
  {
    id: 77,
    product_name: 'Rob',
    category: 0,
    stock: false,
    sku: 21688,
    price: '$880.91',
    qty: 872,
    status: 3,
    image: product4,
    product_brand: 'Auer and Sons',
  },
  {
    id: 78,
    product_name: 'Zamit',
    category: 3,
    stock: true,
    sku: 52982,
    price: '$156.96',
    qty: 836,
    status: 1,
    image: product5,
    product_brand: 'Koss, Heller and Lind',
  },
  {
    id: 79,
    product_name: 'Zoolab',
    category: 3,
    stock: true,
    sku: 65044,
    price: '$991.50',
    qty: 806,
    status: 2,
    image: product5,
    product_brand: 'Brekke Inc',
  },
  {
    id: 80,
    product_name: 'Stronghold',
    category: 0,
    stock: false,
    sku: 78717,
    price: '$716.83',
    qty: 821,
    status: 1,
    image: product5,
    product_brand: 'Balistreri Group',
  },
  {
    id: 81,
    product_name: 'Rintone',
    category: 0,
    stock: false,
    sku: 24204,
    price: '$984.21',
    qty: 395,
    status: 2,
    image: product5,
    product_brand: 'Von, Terry and Wintheiser',
  },
  {
    id: 82,
    product_name: 'Temp',
    category: 0,
    stock: true,
    sku: 26115,
    price: '$405.73',
    qty: 719,
    status: 3,
    image: product5,
    product_brand: 'Batz Group',
  },
  {
    id: 83,
    product_name: 'Rlexidy',
    category: 0,
    stock: false,
    sku: 35053,
    price: '$514.39',
    qty: 286,
    status: 3,
    image: product6,
    product_brand: 'Beer, Blick and Heller',
  },
  {
    id: 84,
    product_name: 'Ronstring',
    category: 0,
    stock: true,
    sku: 63623,
    price: '$910.60',
    qty: 681,
    status: 3,
    image: product6,
    product_brand: 'Carroll, Tremblay and Koch',
  },
  {
    id: 85,
    product_name: 'Rixflex',
    category: 3,
    stock: false,
    sku: 84615,
    price: '$990.12',
    qty: 256,
    status: 1,
    image: product6,
    product_brand: 'Nader-Hane',
  },
  {
    id: 86,
    product_name: 'Uerified',
    category: 0,
    stock: true,
    sku: 34845,
    price: '$677.77',
    qty: 778,
    status: 1,
    image: product6,
    product_brand: 'Bechtelar, Heidenreich and Collins',
  },
  {
    id: 87,
    product_name: 'Stringtough',
    category: 0,
    stock: false,
    sku: 37008,
    price: '$803.24',
    qty: 514,
    status: 1,
    image: product7,
    product_brand: 'Bruen, Connelly and Padberg',
  },
  {
    id: 88,
    product_name: 'Qookley',
    category: 1,
    stock: true,
    sku: 3332,
    price: '$587.09',
    qty: 644,
    status: 1,
    image: product7,
    product_brand: 'Larkin-Wilderman',
  },
  {
    id: 89,
    product_name: 'Zamit',
    category: 3,
    stock: false,
    sku: 30921,
    price: '$338.43',
    qty: 412,
    status: 2,
    image: product7,
    product_brand: 'Okuneva-Wilderman',
  },
  {
    id: 90,
    product_name: 'Mat Lam Tam',
    category: 3,
    stock: true,
    sku: 31016,
    price: '$911.05',
    qty: 814,
    status: 1,
    image: product7,
    product_brand: 'Herman, Wisozk and Watsica',
  },
  {
    id: 91,
    product_name: 'Rt',
    category: 1,
    stock: true,
    sku: 28726,
    price: '$474.40',
    qty: 514,
    status: 3,
    image: product8,
    product_brand: 'Hodkiewicz Inc',
  },
  {
    id: 92,
    product_name: 'Stim',
    category: 0,
    stock: true,
    sku: 44611,
    price: '$115.60',
    qty: 355,
    status: 3,
    image: product8,
    product_brand: 'Swaniawski, West and Runolfsdottir',
  },
  {
    id: 93,
    product_name: 'Rix San',
    category: 0,
    stock: true,
    sku: 94348,
    price: '$602.94',
    qty: 695,
    status: 1,
    image: product8,
    product_brand: 'Wilkinson and Sons',
  },
  {
    id: 94,
    product_name: 'Vagram',
    category: 0,
    stock: true,
    sku: 5786,
    price: '$935.11',
    qty: 944,
    status: 2,
    image: product8,
    product_brand: 'Mante, Greenfelder and Welch',
  },
  {
    id: 95,
    product_name: 'Otcom',
    category: 3,
    stock: true,
    sku: 88662,
    price: '$254.18',
    qty: 6,
    status: 3,
    image: product9,
    product_brand: 'Lakin, Kautzer and Witting',
  },
  {
    id: 96,
    product_name: 'Rixflex',
    category: 1,
    stock: false,
    sku: 37038,
    price: '$871.09',
    qty: 235,
    status: 2,
    image: product9,
    product_brand: 'Cormier-Leuschke',
  },
  {
    id: 97,
    product_name: 'Lotstring',
    category: 1,
    stock: true,
    sku: 55539,
    price: '$711.99',
    qty: 442,
    status: 2,
    image: product9,
    product_brand: 'Cormier-Reichert',
  },
  {
    id: 98,
    product_name: 'Wiodex',
    category: 3,
    stock: true,
    sku: 59067,
    price: '$311.77',
    qty: 787,
    status: 3,
    image: product9,
    product_brand: 'Kohler LLC',
  },
  {
    id: 99,
    product_name: 'Komainer',
    category: 0,
    stock: true,
    sku: 59592,
    price: '$656.85',
    qty: 679,
    status: 3,
    image: product10,
    product_brand: 'Feest Group',
  },
  {
    id: 100,
    product_name: 'Ulpha',
    category: 0,
    stock: false,
    sku: 13501,
    price: '$538.96',
    qty: 822,
    status: 1,
    image: product10,
    product_brand: 'Rosenbaum Group',
  },
]

// eslint-disable-next-line sonarjs/cognitive-complexity
mock.onGet('/apps/ecommerce/products/list').reply(config => {
  const { q = '', stock = undefined, category = null, status = null, options = {} } = config.params ?? {}

  const { sortBy = '', itemsPerPage = 10, page = 1 } = options

  const sort = JSON.parse(JSON.stringify(sortBy))

  console.log(sort)

  const queryLower = q.toLowerCase()

  console.log(category, status, stock)

  console.log('Filetered by stock', database.filter(product =>
    product.stock === (stock || product.stock),
  ))

  // Filtering Products
  let filteredProducts = database.filter(product => (
    (product.product_name.toLowerCase().includes(queryLower) || product.product_brand.toLowerCase().includes(queryLower))
    && product.category === (category || product.category) && product.status === (status || product.status) && product.stock === (stock || product.stock)
  )).reverse()

  // Sort
  if (sort.length) {
    if (sort[0].key === 'product') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.product_name.toLowerCase() > b.product_name.toLowerCase() ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.product_name.toLowerCase() < b.product_name.toLowerCase() ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'category') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.category > b.category ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.category < b.category ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'status') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.status > b.status ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.status < b.status ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'price') {
      filteredProducts = filteredProducts.sort((a, b) => {
        console.log(a.price.slice(1))
        if (sort[0].order === 'asc')
          return Number(a.price.slice(1)) > Number(b.price.slice(1)) ? 1 : -1
        else if (sort[0].order === 'desc')
          return Number(a.price.slice(1)) < Number(b.price.slice(1)) ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'qty') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.qty > b.qty ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.qty < b.qty ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'sku') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.sku > b.sku ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.sku < b.sku ? 1 : -1

        return 0
      })
    }
  }
  console.log(filteredProducts)

  return [200, { products: paginateArray(filteredProducts, itemsPerPage, page), total: filteredProducts.length }]
})
