import type { EcommerceProduct, Review } from '../types'
import mock from '@/@fake-db/mock'
import { paginateArray } from '@/@fake-db/utils'
import avatar1 from '@images/avatars/avatar-1.png'
import avatar10 from '@images/avatars/avatar-10.png'
import avatar11 from '@images/avatars/avatar-11.png'
import avatar12 from '@images/avatars/avatar-12.png'
import avatar13 from '@images/avatars/avatar-13.png'
import avatar14 from '@images/avatars/avatar-14.png'
import avatar15 from '@images/avatars/avatar-15.png'
import avatar2 from '@images/avatars/avatar-2.png'
import avatar3 from '@images/avatars/avatar-3.png'
import avatar4 from '@images/avatars/avatar-4.png'
import avatar5 from '@images/avatars/avatar-5.png'
import avatar6 from '@images/avatars/avatar-6.png'
import avatar7 from '@images/avatars/avatar-7.png'
import avatar8 from '@images/avatars/avatar-8.png'
import avatar9 from '@images/avatars/avatar-9.png'

import product1 from '@images/ecommerce-images/product-1.png'
import product10 from '@images/ecommerce-images/product-10.png'
import product11 from '@images/ecommerce-images/product-11.png'
import product12 from '@images/ecommerce-images/product-12.png'
import product13 from '@images/ecommerce-images/product-13.png'
import product14 from '@images/ecommerce-images/product-14.png'
import product15 from '@images/ecommerce-images/product-15.png'
import product16 from '@images/ecommerce-images/product-16.png'
import product17 from '@images/ecommerce-images/product-17.png'
import product18 from '@images/ecommerce-images/product-18.png'
import product19 from '@images/ecommerce-images/product-19.png'
import product2 from '@images/ecommerce-images/product-2.png'
import product20 from '@images/ecommerce-images/product-20.png'
import product3 from '@images/ecommerce-images/product-3.png'
import product4 from '@images/ecommerce-images/product-4.png'
import product5 from '@images/ecommerce-images/product-5.png'
import product6 from '@images/ecommerce-images/product-6.png'
import product7 from '@images/ecommerce-images/product-7.png'
import product8 from '@images/ecommerce-images/product-8.png'
import product9 from '@images/ecommerce-images/product-9.png'

const products: EcommerceProduct[] = [
  {
    id: 1,
    product_name: 'iPhone 14 Pro',
    category: 2,
    stock: true,
    sku: 19472,
    price: '$999',
    qty: 665,
    status: 3,
    image: product1,
    product_brand: 'Super Retina XDR display footnote Pro Motion technology',
  },
  {
    id: 2,
    product_name: 'Echo Dot (4th Gen)',
    category: 2,
    stock: false,
    sku: 72836,
    price: '$25.50',
    qty: 827,
    status: 2,
    image: product2,
    product_brand: 'Echo Dot Smart speaker with Alexa',
  },
  {
    id: 3,
    product_name: 'Dohioue Wall Clock',
    category: 0,
    stock: false,
    sku: 29540,
    price: '$16.34',
    qty: 804,
    status: 2,
    image: product3,
    product_brand: 'Modern 10 Inch Battery Operated Wall Clocks',
  },
  {
    id: 4,
    product_name: 'INZCOU Running Shoes',
    category: 3,
    stock: false,
    sku: 49402,
    price: '$36.98',
    qty: 528,
    status: 1,
    image: product4,
    product_brand: 'Lightweight Tennis Shoes Non Slip Gym Workout Shoes',
  },
  {
    id: 5,
    product_name: 'Apple Watch Series 7',
    category: 4,
    stock: false,
    sku: 46658,
    price: '$799',
    qty: 851,
    status: 1,
    image: product5,
    product_brand: 'Starlight Aluminum Case with Starlight Sport Band.',
  },
  {
    id: 6,
    product_name: 'Meta Quest 2',
    category: 4,
    stock: true,
    sku: 57640,
    price: '$299',
    qty: 962,
    status: 1,
    image: product6,
    product_brand: 'Advanced All-In-One Virtual Reality Headset',
  },
  {
    id: 7,
    product_name: 'MacBook Pro 16',
    category: 2,
    stock: true,
    sku: 92885,
    price: '$2648.95',
    qty: 965,
    status: 2,
    image: product7,
    product_brand: 'Laptop M2 Pro chip with 12‑core CPU and 19‑core GPU',
  },
  {
    id: 8,
    product_name: 'SAMSUNG Galaxy S22 Ultra',
    category: 2,
    stock: true,
    sku: 75257,
    price: '$899',
    qty: 447,
    status: 2,
    image: product8,
    product_brand: 'Android Smartphone, 256GB, 8K Camera',
  },
  {
    id: 9,
    product_name: 'Air Jordan',
    category: 3,
    stock: false,
    sku: 31063,
    price: '$125',
    qty: 942,
    status: 3,
    image: product9,
    product_brand: 'Air Jordan is a line of basketball shoes produced by Nike',
  },
  {
    id: 10,
    product_name: 'VISKABACKA',
    category: 1,
    stock: false,
    sku: 91848,
    price: '$190.45',
    qty: 133,
    status: 1,
    image: product10,
    product_brand: 'Armchair, Skartofta black/light grey',
  },
  {
    id: 11,
    product_name: 'Nintendo Switch',
    category: 5,
    stock: true,
    sku: 52575,
    price: '$296.99',
    qty: 870,
    status: 3,
    image: product11,
    product_brand: 'TV Mode, Tabletop Mode, Handheld Mode',
  },
  {
    id: 12,
    product_name: 'PlayStation 5',
    category: 5,
    stock: true,
    sku: 59551,
    price: '$499',
    qty: 145,
    status: 1,
    image: product12,
    product_brand: 'Marvel at incredible graphics and experience',
  },
  {
    id: 13,
    product_name: 'Amazon Fire TV',
    category: 2,
    stock: false,
    sku: 5829,
    price: '$263.49',
    qty: 587,
    status: 1,
    image: product13,
    product_brand: '4K UHD smart TV, stream live TV without cable',
  },
  {
    id: 14,
    product_name: 'Smiletag Ceramic Vase',
    category: 1,
    stock: false,
    sku: 24456,
    price: '$34.99',
    qty: 310,
    status: 1,
    image: product14,
    product_brand: 'Modern Farmhouse Decor Vase Set of 3',
  },
  {
    id: 15,
    product_name: 'Apple iPad',
    category: 2,
    stock: true,
    sku: 35946,
    price: '$248.39',
    qty: 468,
    status: 2,
    image: product15,
    product_brand: '10.2-inch Retina Display, 64GB',
  },
  {
    id: 16,
    product_name: 'BANGE Anti Theft Backpack',
    category: 4,
    stock: true,
    sku: 41867,
    price: '$79.99',
    qty: 519,
    status: 3,
    image: product16,
    product_brand: 'Smart Business Laptop Fits 15.6 Inch Notebook',
  },
  {
    id: 17,
    product_name: 'Xbox Series X/S',
    category: 5,
    stock: true,
    sku: 43224,
    price: '$49.99',
    qty: 787,
    status: 2,
    image: product17,
    product_brand: 'Dual Controller Charger Station Dock',
  },
  {
    id: 18,
    product_name: 'Canon EOS Rebel T7',
    category: 2,
    stock: true,
    sku: 63474,
    price: '$399',
    qty: 810,
    status: 1,
    image: product18,
    product_brand: '18-55mm Lens | Built-in Wi-Fi | 24.1 MP CMOS Sensor',
  },
  {
    id: 19,
    product_name: 'Honiway Wall Mirror',
    category: 1,
    stock: false,
    sku: 15859,
    price: '$23.99',
    qty: 735,
    status: 3,
    image: product19,
    product_brand: 'Decorative 12 inch Rustic Wood Mirror Sunburst Boho',
  },
  {
    id: 20,
    product_name: 'Tommaso Veloce Shoes',
    category: 3,
    stock: false,
    sku: 28844,
    price: '$922.09',
    qty: 294,
    status: 3,
    image: product20,
    product_brand: 'Peloton Shoes Triathlon Road Bike Indoor Cycling',
  },
  {
    id: 21,
    product_name: 'Zoolab',
    category: 0,
    stock: true,
    sku: 99009,
    price: '$719.13',
    qty: 927,
    status: 1,
    image: product1,
    product_brand: 'Cruickshank-Jones',
  },
  {
    id: 22,
    product_name: 'Viva',
    category: 1,
    stock: false,
    sku: 53795,
    price: '$775.80',
    qty: 442,
    status: 1,
    image: product2,
    product_brand: 'Ferry Group',
  },
  {
    id: 23,
    product_name: 'Transcof',
    category: 3,
    stock: true,
    sku: 77663,
    price: '$817.60',
    qty: 256,
    status: 2,
    image: product3,
    product_brand: 'Bruen-Heathcote',
  },
  {
    id: 24,
    product_name: 'Uerified',
    category: 0,
    stock: false,
    sku: 45282,
    price: '$167.19',
    qty: 728,
    status: 2,
    image: product4,
    product_brand: 'Koch Group',
  },
  {
    id: 25,
    product_name: 'Y-find',
    category: 1,
    stock: false,
    sku: 5622,
    price: '$189.77',
    qty: 445,
    status: 1,
    image: product5,
    product_brand: 'Emmerich and Sons',
  },
  {
    id: 26,
    product_name: 'Wigtax',
    category: 0,
    stock: true,
    sku: 38920,
    price: '$411.46',
    qty: 857,
    status: 1,
    image: product6,
    product_brand: 'Zulauf-Prohaska',
  },
  {
    id: 27,
    product_name: 'Tempsoft',
    category: 0,
    stock: true,
    sku: 78211,
    price: '$961.76',
    qty: 975,
    status: 2,
    image: product7,
    product_brand: 'VonRueden, Rogahn and Kris',
  },
  {
    id: 28,
    product_name: 'Rt',
    category: 0,
    stock: true,
    sku: 98552,
    price: '$514.14',
    qty: 39,
    status: 2,
    image: product8,
    product_brand: 'Romaguera, O\'Connell and Abernathy',
  },
  {
    id: 29,
    product_name: 'Zontrax',
    category: 3,
    stock: true,
    sku: 7151,
    price: '$591.30',
    qty: 74,
    status: 2,
    image: product9,
    product_brand: 'Mills, Hagenes and Bednar',
  },
  {
    id: 30,
    product_name: 'Keylex',
    category: 0,
    stock: true,
    sku: 79571,
    price: '$928.07',
    qty: 245,
    status: 3,
    image: product10,
    product_brand: 'Sanford, Harvey and Parisian',
  },
  {
    id: 31,
    product_name: 'Trippledex',
    category: 1,
    stock: false,
    sku: 51597,
    price: '$312.03',
    qty: 657,
    status: 3,
    image: product11,
    product_brand: 'Conroy-Bergstrom',
  },
  {
    id: 32,
    product_name: 'Opela',
    category: 0,
    stock: true,
    sku: 6506,
    price: '$951.29',
    qty: 770,
    status: 2,
    image: product12,
    product_brand: 'Langosh Inc',
  },
  {
    id: 33,
    product_name: 'Span',
    category: 3,
    stock: false,
    sku: 33523,
    price: '$600.43',
    qty: 622,
    status: 3,
    image: product13,
    product_brand: 'Jerde-Walsh',
  },
  {
    id: 34,
    product_name: 'Rank',
    category: 0,
    stock: false,
    sku: 60307,
    price: '$337.90',
    qty: 896,
    status: 1,
    image: product14,
    product_brand: 'Barrows, Quitzon and Roberts',
  },
  {
    id: 35,
    product_name: 'Tempsoft',
    category: 0,
    stock: true,
    sku: 75059,
    price: '$959.47',
    qty: 239,
    status: 3,
    image: product15,
    product_brand: 'Russel-Grant',
  },
  {
    id: 36,
    product_name: 'Ventosanzap',
    category: 0,
    stock: true,
    sku: 69072,
    price: '$756.81',
    qty: 410,
    status: 1,
    image: product16,
    product_brand: 'O\'Conner-Zboncak',
  },
  {
    id: 37,
    product_name: 'Mat Lam Tam',
    category: 0,
    stock: false,
    sku: 68290,
    price: '$256.86',
    qty: 630,
    status: 2,
    image: product17,
    product_brand: 'Rutherford, Heller and Bashirian',
  },
  {
    id: 38,
    product_name: 'Zamit',
    category: 3,
    stock: true,
    sku: 89552,
    price: '$378.54',
    qty: 247,
    status: 3,
    image: product18,
    product_brand: 'Swift-Altenwerth',
  },
  {
    id: 39,
    product_name: 'Tresom',
    category: 3,
    stock: true,
    sku: 50863,
    price: '$166.17',
    qty: 672,
    status: 3,
    image: product19,
    product_brand: 'O\'Kon, Waelchi and Lesch',
  },
  {
    id: 40,
    product_name: 'Viva',
    category: 0,
    stock: false,
    sku: 90484,
    price: '$745.76',
    qty: 697,
    status: 2,
    image: product20,
    product_brand: 'Johnston, Anderson and Metz',
  },
  {
    id: 41,
    product_name: 'Matsoft',
    category: 0,
    stock: true,
    sku: 76980,
    price: '$603.16',
    qty: 74,
    status: 2,
    image: product1,
    product_brand: 'O\'Conner, Paucek and Braun',
  },
  {
    id: 42,
    product_name: 'Wiodex',
    category: 1,
    stock: true,
    sku: 66971,
    price: '$772.51',
    qty: 280,
    status: 2,
    image: product2,
    product_brand: 'Wisoky-Kassulke',
  },
  {
    id: 43,
    product_name: 'Keylex',
    category: 3,
    stock: false,
    sku: 16589,
    price: '$986.22',
    qty: 758,
    status: 3,
    image: product3,
    product_brand: 'Haag, Bruen and Reichel',
  },
  {
    id: 44,
    product_name: 'Konklux',
    category: 0,
    stock: true,
    sku: 73896,
    price: '$988.47',
    qty: 14,
    status: 3,
    image: product4,
    product_brand: 'Ankunding Inc',
  },
  {
    id: 45,
    product_name: 'Tresom',
    category: 0,
    stock: false,
    sku: 67489,
    price: '$946.62',
    qty: 35,
    status: 3,
    image: product5,
    product_brand: 'Deckow and Sons',
  },
  {
    id: 46,
    product_name: 'Quo Lux',
    category: 3,
    stock: true,
    sku: 48177,
    price: '$224.28',
    qty: 935,
    status: 1,
    image: product1,
    product_brand: 'Kreiger, Reynolds and Sporer',
  },
  {
    id: 47,
    product_name: 'Roldlamis',
    category: 1,
    stock: true,
    sku: 225,
    price: '$952.14',
    qty: 361,
    status: 2,
    image: product6,
    product_brand: 'Kuphal-Abbott',
  },
  {
    id: 48,
    product_name: 'Tampflex',
    category: 0,
    stock: false,
    sku: 29438,
    price: '$646.21',
    qty: 908,
    status: 1,
    image: product7,
    product_brand: 'Romaguera, Schmeler and Volkman',
  },
  {
    id: 49,
    product_name: 'Span',
    category: 1,
    stock: true,
    sku: 55666,
    price: '$583.13',
    qty: 898,
    status: 1,
    image: product8,
    product_brand: 'Hane-Romaguera',
  },
  {
    id: 50,
    product_name: 'Zamit',
    category: 0,
    stock: false,
    sku: 55860,
    price: '$273.67',
    qty: 332,
    status: 2,
    image: product9,
    product_brand: 'Hoeger-Powlowski',
  },
  {
    id: 51,
    product_name: 'Witchip',
    category: 1,
    stock: false,
    sku: 41156,
    price: '$573.24',
    qty: 55,
    status: 3,
    image: product10,
    product_brand: 'Heidenreich, Keeling and Kuhn',
  },
  {
    id: 52,
    product_name: 'Ratity',
    category: 3,
    stock: true,
    sku: 8147,
    price: '$571.76',
    qty: 839,
    status: 2,
    image: product11,
    product_brand: 'Beier and Sons',
  },
  {
    id: 53,
    product_name: 'Voltsillam',
    category: 1,
    stock: true,
    sku: 78814,
    price: '$396.79',
    qty: 496,
    status: 2,
    image: product12,
    product_brand: 'Jones and Sons',
  },
  {
    id: 54,
    product_name: 'Voltsillam',
    category: 3,
    stock: false,
    sku: 96040,
    price: '$140.79',
    qty: 50,
    status: 1,
    image: product13,
    product_brand: 'Mohr and Sons',
  },
  {
    id: 55,
    product_name: 'Matsoft',
    category: 0,
    stock: true,
    sku: 99482,
    price: '$723.01',
    qty: 453,
    status: 1,
    image: product1,
    product_brand: 'Kling-Hayes',
  },
  {
    id: 56,
    product_name: 'Rt',
    category: 0,
    stock: true,
    sku: 56480,
    price: '$849.72',
    qty: 293,
    status: 3,
    image: product14,
    product_brand: 'Brekke-Lubowitz',
  },
  {
    id: 57,
    product_name: 'Konklab',
    category: 0,
    stock: true,
    sku: 95499,
    price: '$152.02',
    qty: 263,
    status: 2,
    image: product15,
    product_brand: 'Kiehn LLC',
  },
  {
    id: 58,
    product_name: 'Lotstring',
    category: 0,
    stock: false,
    sku: 83893,
    price: '$111.29',
    qty: 231,
    status: 3,
    image: product16,
    product_brand: 'Windler-Corwin',
  },
  {
    id: 59,
    product_name: 'Keylex',
    category: 3,
    stock: true,
    sku: 24943,
    price: '$148.67',
    qty: 289,
    status: 3,
    image: product17,
    product_brand: 'Reynolds, Buckridge and Schmeler',
  },
  {
    id: 60,
    product_name: 'Transcof',
    category: 0,
    stock: false,
    sku: 92258,
    price: '$369.54',
    qty: 268,
    status: 1,
    image: product18,
    product_brand: 'Jacobs-Farrell',
  },
  {
    id: 61,
    product_name: 'Opela',
    category: 0,
    stock: true,
    sku: 15281,
    price: '$890.33',
    qty: 115,
    status: 2,
    image: product19,
    product_brand: 'Beier-Bergstrom',
  },
  {
    id: 62,
    product_name: 'Rlowdesk',
    category: 0,
    stock: false,
    sku: 92346,
    price: '$668.81',
    qty: 850,
    status: 1,
    image: product20,
    product_brand: 'Roob and Sons',
  },
  {
    id: 63,
    product_name: 'Kanlam',
    category: 0,
    stock: false,
    sku: 8590,
    price: '$407.46',
    qty: 547,
    status: 3,
    image: product2,
    product_brand: 'Hauck Group',
  },
  {
    id: 64,
    product_name: 'Rembucket',
    category: 0,
    stock: false,
    sku: 57694,
    price: '$763.28',
    qty: 188,
    status: 1,
    image: product2,
    product_brand: 'Reynolds-Lindgren',
  },
  {
    id: 65,
    product_name: 'Tin',
    category: 0,
    stock: false,
    sku: 83532,
    price: '$866.51',
    qty: 469,
    status: 3,
    image: product2,
    product_brand: 'Stroman and Sons',
  },
  {
    id: 66,
    product_name: 'Trippledex',
    category: 0,
    stock: false,
    sku: 85878,
    price: '$390.28',
    qty: 753,
    status: 2,
    image: product2,
    product_brand: 'Kihn-Wisoky',
  },
  {
    id: 67,
    product_name: 'Redhold',
    category: 0,
    stock: false,
    sku: 18810,
    price: '$944.68',
    qty: 783,
    status: 3,
    image: product2,
    product_brand: 'Konopelski-Hauck',
  },
  {
    id: 68,
    product_name: 'Pannier',
    category: 3,
    stock: false,
    sku: 42375,
    price: '$802.49',
    qty: 371,
    status: 1,
    image: product3,
    product_brand: 'Rau Inc',
  },
  {
    id: 69,
    product_name: 'Rlexidy',
    category: 0,
    stock: true,
    sku: 55165,
    price: '$812.75',
    qty: 981,
    status: 3,
    image: product3,
    product_brand: 'Torp-Lebsack',
  },
  {
    id: 70,
    product_name: 'Keylex',
    category: 1,
    stock: false,
    sku: 92443,
    price: '$338.64',
    qty: 44,
    status: 1,
    image: product3,
    product_brand: 'Hane-Bednar',
  },
  {
    id: 71,
    product_name: 'Kuobam',
    category: 0,
    stock: false,
    sku: 98203,
    price: '$190.82',
    qty: 212,
    status: 1,
    image: product3,
    product_brand: 'Rice Group',
  },
  {
    id: 72,
    product_name: 'Ulphazap',
    category: 1,
    stock: false,
    sku: 49451,
    price: '$658.79',
    qty: 707,
    status: 3,
    image: product3,
    product_brand: 'West, White and Rau',
  },
  {
    id: 73,
    product_name: 'Wiodex',
    category: 0,
    stock: true,
    sku: 48644,
    price: '$231.38',
    qty: 513,
    status: 3,
    image: product4,
    product_brand: 'Keeling-Dicki',
  },
  {
    id: 74,
    product_name: 'Veribet',
    category: 0,
    stock: true,
    sku: 86347,
    price: '$885.15',
    qty: 953,
    status: 2,
    image: product4,
    product_brand: 'Gerlach, Bernhard and Schmidt',
  },
  {
    id: 75,
    product_name: 'Rix San',
    category: 0,
    stock: true,
    sku: 53970,
    price: '$897.45',
    qty: 305,
    status: 3,
    image: product4,
    product_brand: 'Emmerich, Hills and Beer',
  },
  {
    id: 76,
    product_name: 'Zoolab',
    category: 0,
    stock: false,
    sku: 64602,
    price: '$753.84',
    qty: 269,
    status: 1,
    image: product4,
    product_brand: 'Treutel-Dickinson',
  },
  {
    id: 77,
    product_name: 'Rob',
    category: 0,
    stock: false,
    sku: 21688,
    price: '$880.91',
    qty: 872,
    status: 3,
    image: product4,
    product_brand: 'Auer and Sons',
  },
  {
    id: 78,
    product_name: 'Zamit',
    category: 3,
    stock: true,
    sku: 52982,
    price: '$156.96',
    qty: 836,
    status: 1,
    image: product5,
    product_brand: 'Koss, Heller and Lind',
  },
  {
    id: 79,
    product_name: 'Zoolab',
    category: 3,
    stock: true,
    sku: 65044,
    price: '$991.50',
    qty: 806,
    status: 2,
    image: product5,
    product_brand: 'Brekke Inc',
  },
  {
    id: 80,
    product_name: 'Stronghold',
    category: 0,
    stock: false,
    sku: 78717,
    price: '$716.83',
    qty: 821,
    status: 1,
    image: product5,
    product_brand: 'Balistreri Group',
  },
  {
    id: 81,
    product_name: 'Rintone',
    category: 0,
    stock: false,
    sku: 24204,
    price: '$984.21',
    qty: 395,
    status: 2,
    image: product5,
    product_brand: 'Von, Terry and Wintheiser',
  },
  {
    id: 82,
    product_name: 'Temp',
    category: 0,
    stock: true,
    sku: 26115,
    price: '$405.73',
    qty: 719,
    status: 3,
    image: product5,
    product_brand: 'Batz Group',
  },
  {
    id: 83,
    product_name: 'Rlexidy',
    category: 0,
    stock: false,
    sku: 35053,
    price: '$514.39',
    qty: 286,
    status: 3,
    image: product6,
    product_brand: 'Beer, Blick and Heller',
  },
  {
    id: 84,
    product_name: 'Ronstring',
    category: 0,
    stock: true,
    sku: 63623,
    price: '$910.60',
    qty: 681,
    status: 3,
    image: product6,
    product_brand: 'Carroll, Tremblay and Koch',
  },
  {
    id: 85,
    product_name: 'Rixflex',
    category: 3,
    stock: false,
    sku: 84615,
    price: '$990.12',
    qty: 256,
    status: 1,
    image: product6,
    product_brand: 'Nader-Hane',
  },
  {
    id: 86,
    product_name: 'Uerified',
    category: 0,
    stock: true,
    sku: 34845,
    price: '$677.77',
    qty: 778,
    status: 1,
    image: product6,
    product_brand: 'Bechtelar, Heidenreich and Collins',
  },
  {
    id: 87,
    product_name: 'Stringtough',
    category: 0,
    stock: false,
    sku: 37008,
    price: '$803.24',
    qty: 514,
    status: 1,
    image: product7,
    product_brand: 'Bruen, Connelly and Padberg',
  },
  {
    id: 88,
    product_name: 'Qookley',
    category: 1,
    stock: true,
    sku: 3332,
    price: '$587.09',
    qty: 644,
    status: 1,
    image: product7,
    product_brand: 'Larkin-Wilderman',
  },
  {
    id: 89,
    product_name: 'Zamit',
    category: 3,
    stock: false,
    sku: 30921,
    price: '$338.43',
    qty: 412,
    status: 2,
    image: product7,
    product_brand: 'Okuneva-Wilderman',
  },
  {
    id: 90,
    product_name: 'Mat Lam Tam',
    category: 3,
    stock: true,
    sku: 31016,
    price: '$911.05',
    qty: 814,
    status: 1,
    image: product7,
    product_brand: 'Herman, Wisozk and Watsica',
  },
  {
    id: 91,
    product_name: 'Rt',
    category: 1,
    stock: true,
    sku: 28726,
    price: '$474.40',
    qty: 514,
    status: 3,
    image: product8,
    product_brand: 'Hodkiewicz Inc',
  },
  {
    id: 92,
    product_name: 'Stim',
    category: 0,
    stock: true,
    sku: 44611,
    price: '$115.60',
    qty: 355,
    status: 3,
    image: product8,
    product_brand: 'Swaniawski, West and Runolfsdottir',
  },
  {
    id: 93,
    product_name: 'Rix San',
    category: 0,
    stock: true,
    sku: 94348,
    price: '$602.94',
    qty: 695,
    status: 1,
    image: product8,
    product_brand: 'Wilkinson and Sons',
  },
  {
    id: 94,
    product_name: 'Vagram',
    category: 0,
    stock: true,
    sku: 5786,
    price: '$935.11',
    qty: 944,
    status: 2,
    image: product8,
    product_brand: 'Mante, Greenfelder and Welch',
  },
  {
    id: 95,
    product_name: 'Otcom',
    category: 3,
    stock: true,
    sku: 88662,
    price: '$254.18',
    qty: 6,
    status: 3,
    image: product9,
    product_brand: 'Lakin, Kautzer and Witting',
  },
  {
    id: 96,
    product_name: 'Rixflex',
    category: 1,
    stock: false,
    sku: 37038,
    price: '$871.09',
    qty: 235,
    status: 2,
    image: product9,
    product_brand: 'Cormier-Leuschke',
  },
  {
    id: 97,
    product_name: 'Lotstring',
    category: 1,
    stock: true,
    sku: 55539,
    price: '$711.99',
    qty: 442,
    status: 2,
    image: product9,
    product_brand: 'Cormier-Reichert',
  },
  {
    id: 98,
    product_name: 'Wiodex',
    category: 3,
    stock: true,
    sku: 59067,
    price: '$311.77',
    qty: 787,
    status: 3,
    image: product9,
    product_brand: 'Kohler LLC',
  },
  {
    id: 99,
    product_name: 'Komainer',
    category: 0,
    stock: true,
    sku: 59592,
    price: '$656.85',
    qty: 679,
    status: 3,
    image: product10,
    product_brand: 'Feest Group',
  },
  {
    id: 100,
    product_name: 'Ulpha',
    category: 0,
    stock: false,
    sku: 13501,
    price: '$538.96',
    qty: 822,
    status: 1,
    image: product10,
    product_brand: 'Rosenbaum Group',
  },
]

const reviews: Review[] = [
  {
    id: 1,
    product: 'iPhone 14 Pro',
    company_name: 'Super Retina XDR display footnote Pro Motion technology',
    product_image: product1,
    reviewer: 'Zane Scraggs',
    email: 'zscraggs0@flavors.me',
    avatar: avatar1,
    date: '5/28/2020',
    status: 'Published',
    review: 2,
    head: 'lorem ipsum dolor',
    para: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
  },
  {
    id: 2,
    product: 'Echo Dot (4th Gen)',
    company_name: 'Echo Dot Smart speaker with Alexa',
    product_image: product2,
    reviewer: 'Stacey Hallgalley',
    email: 'shallgalley1@google.nl',
    avatar: avatar2,
    date: '3/21/2021',
    status: 'Published',
    review: 5,
    head: 'libero ut',
    para: 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
  },
  {
    id: 3,
    product: 'Dohioue Wall Clock',
    company_name: 'Modern 10 Inch Battery Operated Wall Clocks',
    product_image: product3,
    reviewer: 'Francyne Coulthurst',
    email: 'fcoulthurst2@upenn.edu',
    avatar: avatar3,
    date: '8/10/2020',
    status: 'Published',
    review: 2,
    head: 'neque libero convallis',
    para: 'Phasellus in felis. Donec semper sapien a libero. Nam dui.',
  },
  {
    id: 4,
    product: 'INZCOU Running Shoes',
    company_name: 'Lightweight Tennis Shoes Non Slip Gym Workout Shoes',
    product_image: product4,
    reviewer: 'Nate De Mitris',
    email: 'nde3@intel.com',
    avatar: avatar4,
    date: '12/18/2021',
    status: 'Pending',
    review: 3,
    head: 'accumsan tellus nisi eu',
    para: 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
  },
  {
    id: 5,
    product: 'Apple Watch Series 7',
    company_name: 'Starlight Aluminum Case with Starlight Sport Band.',
    product_image: product5,
    reviewer: 'Ethel Zanardii',
    email: 'ezanardii4@mapy.cz',
    avatar: avatar5,
    date: '6/12/2020',
    status: 'Pending',
    review: 1,
    head: 'etiam faucibus cursus',
    para: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
  },
  {
    id: 6,
    product: 'Meta Quest 2',
    company_name: 'Advanced All-In-One Virtual Reality Headset',
    product_image: product6,
    reviewer: 'Fancy Tweedell',
    email: 'ftweedell5@telegraph.co.uk',
    avatar: avatar6,
    date: '11/23/2020',
    status: 'Pending',
    review: 1,
    head: 'in faucibus orci luctus et',
    para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
  },
  {
    id: 7,
    product: 'MacBook Pro 16',
    company_name: 'Laptop M2 Pro chip with 12‑core CPU and 19‑core GPU',
    product_image: product7,
    reviewer: 'Abeu Gregorace',
    email: 'agregorace6@godaddy.com',
    avatar: avatar7,
    date: '9/8/2020',
    status: 'Pending',
    review: 2,
    head: 'vel enim',
    para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
  },
  {
    id: 8,
    product: 'SAMSUNG Galaxy S22 Ultra',
    company_name: 'Android Smartphone, 256GB, 8K Camera',
    product_image: product8,
    reviewer: 'Sibylle Goodacre',
    email: 'sgoodacre7@washingtonpost.com',
    avatar: avatar8,
    date: '6/10/2021',
    status: 'Pending',
    review: 1,
    head: 'eget semper rutrum',
    para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
  },
  {
    id: 9,
    product: 'Air Jordan',
    company_name: 'Air Jordan is a line of basketball shoes produced by Nike',
    product_image: product9,
    reviewer: 'Gisela Leppard',
    email: 'gleppard8@yandex.ru',
    avatar: avatar9,
    date: '4/20/2020',
    status: 'Published',
    review: 2,
    head: 'ut mauris',
    para: 'Fusce consequat. Nulla nisl. Nunc nisl.',
  },
  {
    id: 10,
    product: 'VISKABACKA',
    company_name: 'Armchair, Skartofta black/light grey',
    product_image: product10,
    reviewer: 'Hilario Wheldon',
    email: 'hwheldon9@apple.com',
    avatar: avatar10,
    date: '8/21/2020',
    status: 'Pending',
    review: 2,
    head: 'amet consectetuer adipiscing elit proin',
    para: 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
  },
  {
    id: 11,
    product: 'Nintendo Switch',
    company_name: 'TV Mode, Tabletop Mode, Handheld Mode',
    product_image: product11,
    reviewer: 'Ivie McGlaughn',
    email: 'imcglaughna@mapquest.com',
    avatar: avatar11,
    date: '4/13/2020',
    status: 'Pending',
    review: 4,
    head: 'eget nunc donec',
    para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
  },
  {
    id: 12,
    product: 'PlayStation 5',
    company_name: 'Marvel at incredible graphics and experience',
    product_image: product12,
    reviewer: 'Neel Kingscott',
    email: 'nkingscottb@soup.io',
    avatar: avatar12,
    date: '12/27/2020',
    status: 'Published',
    review: 1,
    head: 'lacus at velit',
    para: 'Phasellus in felis. Donec semper sapien a libero. Nam dui.',
  },
  {
    id: 13,
    product: 'Amazon Fire TV',
    company_name: '4K UHD smart TV, stream live TV without cable',
    product_image: product13,
    reviewer: 'Tracey Ventham',
    email: 'tventhamc@thetimes.co.uk',
    avatar: avatar13,
    date: '3/17/2021',
    status: 'Published',
    review: 3,
    head: 'at nunc commodo placerat praesent',
    para: 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
  },
  {
    id: 14,
    product: 'Smiletag Ceramic Vase',
    company_name: 'Modern Farmhouse Decor Vase Set of 3',
    product_image: product14,
    reviewer: 'Rollo Truckell',
    email: 'rtruckelld@gravatar.com',
    avatar: avatar14,
    date: '2/23/2020',
    status: 'Published',
    review: 5,
    head: 'in hac',
    para: 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
  },
  {
    id: 15,
    product: 'Apple iPad',
    company_name: '10.2-inch Retina Display, 64GB',
    product_image: product15,
    reviewer: 'Jabez Heggs',
    email: 'jheggse@nba.com',
    avatar: avatar15,
    date: '4/21/2020',
    status: 'Published',
    review: 1,
    head: 'ac consequat',
    para: 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
  },
  {
    id: 16,
    product: 'BANGE Anti Theft Backpack',
    company_name: 'Smart Business Laptop Fits 15.6 Inch Notebook',
    product_image: product16,
    reviewer: 'Micaela Rowesby',
    email: 'mrowesbyf@surveymonkey.com',
    avatar: avatar1,
    date: '12/11/2021',
    status: 'Published',
    review: 1,
    head: 'mattis egestas metus',
    para: 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
  },
  {
    id: 17,
    product: 'Xbox Series X/S',
    company_name: 'Dual Controller Charger Station Dock',
    product_image: product17,
    reviewer: 'Blakelee Benza',
    email: 'bbenzag@utexas.edu',
    avatar: avatar2,
    date: '4/26/2021',
    status: 'Published',
    review: 1,
    head: 'sapien placerat',
    para: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
  },
  {
    id: 18,
    product: 'Canon EOS Rebel T7',
    company_name: '18-55mm Lens | Built-in Wi-Fi | 24.1 MP CMOS Sensor',
    product_image: product18,
    reviewer: 'Emery Breitling',
    email: 'ebreitlingh@friendfeed.com',
    avatar: avatar1,
    date: '12/1/2020',
    status: 'Pending',
    review: 5,
    head: 'nec nisi vulputate',
    para: 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
  },
  {
    id: 19,
    product: 'Honiway Wall Mirror',
    company_name: 'Decorative 12 inch Rustic Wood Mirror Sunburst Boho',
    product_image: product19,
    reviewer: 'Wilona Fields',
    email: 'wfieldsi@columbia.edu',
    avatar: avatar1,
    date: '3/30/2020',
    status: 'Published',
    review: 1,
    head: 'parturient montes nascetur ridiculus',
    para: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',
  },
  {
    id: 20,
    product: 'Tommaso Veloce Shoes',
    company_name: 'Peloton Shoes Triathlon Road Bike Indoor Cycling',
    product_image: product20,
    reviewer: 'Janey Lamprecht',
    email: 'jlamprechtj@tuttocitta.it',
    avatar: avatar1,
    date: '9/16/2020',
    status: 'Pending',
    review: 1,
    head: 'maecenas ut massa quis augue',
    para: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
  },
  {
    id: 21,
    product: 'Zoolab',
    company_name: 'Cruickshank-Jones',
    product_image: product1,
    reviewer: 'Rosene Walsh',
    email: 'rwalshk@latimes.com',
    avatar: avatar1,
    date: '7/17/2021',
    status: 'Published',
    review: 1,
    head: 'convallis nulla',
    para: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
  },
  {
    id: 22,
    product: 'Viva',
    company_name: 'Ferry Group',
    product_image: product2,
    reviewer: 'Buffy Sellen',
    email: 'bsellenl@qq.com',
    avatar: avatar1,
    date: '1/9/2021',
    status: 'Pending',
    review: 3,
    head: 'nunc viverra dapibus',
    para: 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
  },
  {
    id: 23,
    product: 'Transcof',
    company_name: 'Bruen-Heathcote',
    product_image: product3,
    reviewer: 'Alvis Szymanzyk',
    email: 'aszymanzykm@google.cn',
    avatar: avatar1,
    date: '6/11/2020',
    status: 'Pending',
    review: 1,
    head: 'nullam porttitor',
    para: 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
  },
  {
    id: 24,
    product: 'Uerified',
    company_name: 'Koch Group',
    product_image: product4,
    reviewer: 'Hatty Morsley',
    email: 'hmorsleyn@gov.uk',
    avatar: avatar1,
    date: '2/12/2021',
    status: 'Published',
    review: 2,
    head: 'metus sapien ut',
    para: 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
  },
  {
    id: 25,
    product: 'Y-find',
    company_name: 'Emmerich and Sons',
    product_image: product5,
    reviewer: 'Jabez Pudner',
    email: 'jpudnero@cpanel.net',
    avatar: avatar1,
    date: '10/14/2021',
    status: 'Pending',
    review: 4,
    head: 'orci luctus et',
    para: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
  },
  {
    id: 26,
    product: 'Wigtax',
    company_name: 'Zulauf-Prohaska',
    product_image: product6,
    reviewer: 'Ida Ovill',
    email: 'iovillp@newsvine.com',
    avatar: avatar1,
    date: '11/18/2020',
    status: 'Published',
    review: 2,
    head: 'vestibulum ante ipsum',
    para: 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
  },
  {
    id: 27,
    product: 'Tempsoft',
    company_name: 'VonRueden, Rogahn and Kris',
    product_image: product7,
    reviewer: 'Suzanne Breckin',
    email: 'sbreckinq@jimdo.com',
    avatar: avatar1,
    date: '7/26/2020',
    status: 'Published',
    review: 2,
    head: 'vel enim',
    para: 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
  },
  {
    id: 28,
    product: 'Rt',
    company_name: 'Romaguera, O\'Connell and Abernathy',
    product_image: product8,
    reviewer: 'Morgana Coote',
    email: 'mcooter@tinypic.com',
    avatar: avatar1,
    date: '8/29/2021',
    status: 'Pending',
    review: 5,
    head: 'cubilia curae mauris',
    para: 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
  },
  {
    id: 29,
    product: 'Zontrax',
    company_name: 'Mills, Hagenes and Bednar',
    product_image: product9,
    reviewer: 'Wesley Murra',
    email: 'wmurras@tumblr.com',
    avatar: avatar1,
    date: '3/20/2021',
    status: 'Pending',
    review: 4,
    head: 'gravida nisi at',
    para: 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
  },
  {
    id: 30,
    product: 'Keylex',
    company_name: 'Sanford, Harvey and Parisian',
    product_image: product10,
    reviewer: 'Jobye Varnam',
    email: 'jvarnamt@webs.com',
    avatar: avatar1,
    date: '11/24/2020',
    status: 'Pending',
    review: 2,
    head: 'nec sem',
    para: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
  },
  {
    id: 31,
    product: 'Trippledex',
    company_name: 'Conroy-Bergstrom',
    product_image: product11,
    reviewer: 'Bibbye O\'Dowd',
    email: 'bodowdu@infoseek.co.jp',
    avatar: avatar1,
    date: '7/7/2020',
    status: 'Published',
    review: 5,
    head: 'odio elementum eu',
    para: 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
  },
  {
    id: 32,
    product: 'Opela',
    company_name: 'Langosh Inc',
    product_image: product12,
    reviewer: 'Baldwin Bodimeade',
    email: 'bbodimeadev@gnu.org',
    avatar: avatar1,
    date: '3/21/2020',
    status: 'Published',
    review: 2,
    head: 'in imperdiet et commodo',
    para: 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
  },
  {
    id: 33,
    product: 'Span',
    company_name: 'Jerde-Walsh',
    product_image: product13,
    reviewer: 'Rozalin Allan',
    email: 'rallanw@ucsd.edu',
    avatar: avatar1,
    date: '1/23/2020',
    status: 'Published',
    review: 4,
    head: 'pellentesque at',
    para: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
  },
  {
    id: 34,
    product: 'Rank',
    company_name: 'Barrows, Quitzon and Roberts',
    product_image: product14,
    reviewer: 'Patsy Bowlas',
    email: 'pbowlasx@yandex.ru',
    avatar: avatar1,
    date: '10/7/2020',
    status: 'Pending',
    review: 5,
    head: 'congue etiam',
    para: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
  },
  {
    id: 35,
    product: 'Tempsoft',
    company_name: 'Russel-Grant',
    product_image: product15,
    reviewer: 'Zsazsa Jansens',
    email: 'zjansensy@wikipedia.org',
    avatar: avatar1,
    date: '8/7/2021',
    status: 'Pending',
    review: 1,
    head: 'eget eros',
    para: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
  },
  {
    id: 36,
    product: 'Ventosanzap',
    company_name: 'O\'Conner-Zboncak',
    product_image: product16,
    reviewer: 'Denny MacGettigen',
    email: 'dmacgettigenz@ca.gov',
    avatar: avatar1,
    date: '2/17/2020',
    status: 'Published',
    review: 1,
    head: 'vel dapibus',
    para: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
  },
  {
    id: 37,
    product: 'Mat Lam Tam',
    company_name: 'Rutherford, Heller and Bashirian',
    product_image: product17,
    reviewer: 'Leia Braunroth',
    email: 'lbraunroth10@nytimes.com',
    avatar: avatar1,
    date: '1/28/2021',
    status: 'Published',
    review: 4,
    head: 'sit amet consectetuer',
    para: 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
  },
  {
    id: 38,
    product: 'Zamit',
    company_name: 'Swift-Altenwerth',
    product_image: product18,
    reviewer: 'Nil Vasilic',
    email: 'nvasilic11@ft.com',
    avatar: avatar1,
    date: '1/2/2020',
    status: 'Published',
    review: 1,
    head: 'blandit non',
    para: 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
  },
  {
    id: 39,
    product: 'Tresom',
    company_name: 'O\'Kon, Waelchi and Lesch',
    product_image: product19,
    reviewer: 'Mandie Forseith',
    email: 'mforseith12@phpbb.com',
    avatar: avatar1,
    date: '7/2/2020',
    status: 'Published',
    review: 1,
    head: 'in ante vestibulum ante',
    para: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
  },
  {
    id: 40,
    product: 'Viva',
    company_name: 'Johnston, Anderson and Metz',
    product_image: product20,
    reviewer: 'Audra Pinks',
    email: 'apinks13@pinterest.com',
    avatar: avatar1,
    date: '1/6/2020',
    status: 'Pending',
    review: 2,
    head: 'ante ipsum primis in',
    para: 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
  },
  {
    id: 41,
    product: 'Matsoft',
    company_name: 'O\'Conner, Paucek and Braun',
    product_image: product1,
    reviewer: 'Damita Jarad',
    email: 'djarad14@un.org',
    avatar: avatar1,
    date: '10/30/2021',
    status: 'Pending',
    review: 4,
    head: 'mus etiam vel augue',
    para: 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
  },
  {
    id: 42,
    product: 'Wiodex',
    company_name: 'Wisoky-Kassulke',
    product_image: product2,
    reviewer: 'Fowler Drury',
    email: 'fdrury15@chicagotribune.com',
    avatar: avatar1,
    date: '2/11/2020',
    status: 'Published',
    review: 3,
    head: 'dictumst aliquam augue quam',
    para: 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
  },
  {
    id: 43,
    product: 'Keylex',
    company_name: 'Haag, Bruen and Reichel',
    product_image: product3,
    reviewer: 'Anette Jouen',
    email: 'ajouen16@admin.ch',
    avatar: avatar1,
    date: '12/11/2020',
    status: 'Published',
    review: 3,
    head: 'mauris non ligula pellentesque ultrices',
    para: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
  },
  {
    id: 44,
    product: 'Konklux',
    company_name: 'Ankunding Inc',
    product_image: product4,
    reviewer: 'Candace Fossey',
    email: 'cfossey17@live.com',
    avatar: avatar1,
    date: '2/10/2021',
    status: 'Pending',
    review: 1,
    head: 'vel augue vestibulum ante',
    para: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
  },
  {
    id: 45,
    product: 'Tresom',
    company_name: 'Deckow and Sons',
    product_image: product5,
    reviewer: 'Persis Loades',
    email: 'ploades18@g.co',
    avatar: avatar1,
    date: '9/11/2020',
    status: 'Pending',
    review: 5,
    head: 'convallis nulla neque',
    para: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
  },
  {
    id: 46,
    product: 'Quo Lux',
    company_name: 'Kreiger, Reynolds and Sporer',
    product_image: product1,
    reviewer: 'Kim Carrel',
    email: 'kcarrel19@webnode.com',
    avatar: avatar1,
    date: '5/26/2020',
    status: 'Pending',
    review: 3,
    head: 'quam turpis adipiscing lorem',
    para: 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
  },
  {
    id: 47,
    product: 'Roldlamis',
    company_name: 'Kuphal-Abbott',
    product_image: product6,
    reviewer: 'Rodger Broz',
    email: 'rbroz1a@omniture.com',
    avatar: avatar1,
    date: '10/5/2020',
    status: 'Pending',
    review: 1,
    head: 'morbi non',
    para: 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
  },
  {
    id: 48,
    product: 'Tampflex',
    company_name: 'Romaguera, Schmeler and Volkman',
    product_image: product7,
    reviewer: 'Lauri Shearsby',
    email: 'lshearsby1b@goo.ne.jp',
    avatar: avatar1,
    date: '10/18/2020',
    status: 'Pending',
    review: 5,
    head: 'vel dapibus at diam',
    para: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
  },
  {
    id: 49,
    product: 'Span',
    company_name: 'Hane-Romaguera',
    product_image: product8,
    reviewer: 'Hannah Drohun',
    email: 'hdrohun1c@marketwatch.com',
    avatar: avatar1,
    date: '9/14/2020',
    status: 'Pending',
    review: 4,
    head: 'morbi porttitor lorem',
    para: 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
  },
  {
    id: 50,
    product: 'Zamit',
    company_name: 'Hoeger-Powlowski',
    product_image: product9,
    reviewer: 'Celesta Hadden',
    email: 'chadden1d@hao123.com',
    avatar: avatar1,
    date: '4/15/2020',
    status: 'Published',
    review: 5,
    head: 'non sodales',
    para: 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
  },
  {
    id: 51,
    product: 'Witchip',
    company_name: 'Heidenreich, Keeling and Kuhn',
    product_image: product10,
    reviewer: 'Sollie Dowling',
    email: 'sdowling1e@businessweek.com',
    avatar: avatar1,
    date: '9/7/2020',
    status: 'Pending',
    review: 1,
    head: 'nam congue risus semper porta',
    para: 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
  },
  {
    id: 52,
    product: 'Ratity',
    company_name: 'Beier and Sons',
    product_image: product11,
    reviewer: 'Esma Tamsett',
    email: 'etamsett1f@arstechnica.com',
    avatar: avatar1,
    date: '12/21/2020',
    status: 'Pending',
    review: 2,
    head: 'rutrum rutrum neque aenean auctor',
    para: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
  },
  {
    id: 53,
    product: 'Voltsillam',
    company_name: 'Jones and Sons',
    product_image: product12,
    reviewer: 'Fee Pieche',
    email: 'fpieche1g@usa.gov',
    avatar: avatar1,
    date: '4/28/2020',
    status: 'Pending',
    review: 5,
    head: 'non mi',
    para: 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
  },
  {
    id: 54,
    product: 'Voltsillam',
    company_name: 'Mohr and Sons',
    product_image: product13,
    reviewer: 'Frankie Davis',
    email: 'fdavis1h@guardian.co.uk',
    avatar: avatar1,
    date: '3/16/2021',
    status: 'Published',
    review: 5,
    head: 'maecenas pulvinar lobortis est phasellus',
    para: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
  },
  {
    id: 55,
    product: 'Matsoft',
    company_name: 'Kling-Hayes',
    product_image: product1,
    reviewer: 'Byram Wimlet',
    email: 'bwimlet1i@craigslist.org',
    avatar: avatar1,
    date: '7/13/2021',
    status: 'Pending',
    review: 2,
    head: 'tortor sollicitudin',
    para: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',
  },
  {
    id: 56,
    product: 'Rt',
    company_name: 'Brekke-Lubowitz',
    product_image: product14,
    reviewer: 'Maurita Hutchin',
    email: 'mhutchin1j@ibm.com',
    avatar: avatar1,
    date: '11/11/2020',
    status: 'Pending',
    review: 1,
    head: 'odio cras mi pede malesuada',
    para: 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
  },
  {
    id: 57,
    product: 'Konklab',
    company_name: 'Kiehn LLC',
    product_image: product15,
    reviewer: 'Gorden Leftley',
    email: 'gleftley1k@disqus.com',
    avatar: avatar1,
    date: '9/19/2021',
    status: 'Published',
    review: 3,
    head: 'sed nisl nunc rhoncus',
    para: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
  },
  {
    id: 58,
    product: 'Lotstring',
    company_name: 'Windler-Corwin',
    product_image: product16,
    reviewer: 'Raviv Critcher',
    email: 'rcritcher1l@icq.com',
    avatar: avatar1,
    date: '4/20/2020',
    status: 'Published',
    review: 5,
    head: 'bibendum imperdiet nullam orci',
    para: 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
  },
  {
    id: 59,
    product: 'Keylex',
    company_name: 'Reynolds, Buckridge and Schmeler',
    product_image: product17,
    reviewer: 'Cinda Tersay',
    email: 'ctersay1m@berkeley.edu',
    avatar: avatar1,
    date: '3/31/2021',
    status: 'Published',
    review: 4,
    head: 'curabitur at',
    para: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
  },
  {
    id: 60,
    product: 'Transcof',
    company_name: 'Jacobs-Farrell',
    product_image: product18,
    reviewer: 'Raynell Rosenauer',
    email: 'rrosenauer1n@360.cn',
    avatar: avatar1,
    date: '6/3/2020',
    status: 'Published',
    review: 2,
    head: 'massa donec dapibus duis at',
    para: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
  },
  {
    id: 61,
    product: 'Opela',
    company_name: 'Beier-Bergstrom',
    product_image: product19,
    reviewer: 'Aurelia Cooley',
    email: 'acooley1o@prnewswire.com',
    avatar: avatar1,
    date: '7/27/2020',
    status: 'Pending',
    review: 1,
    head: 'dictumst maecenas',
    para: 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
  },
  {
    id: 62,
    product: 'Rlowdesk',
    company_name: 'Roob and Sons',
    product_image: product20,
    reviewer: 'Silvester Vittel',
    email: 'svittel1p@eepurl.com',
    avatar: avatar1,
    date: '3/2/2021',
    status: 'Pending',
    review: 5,
    head: 'elit ac nulla',
    para: 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
  },
  {
    id: 63,
    product: 'Kanlam',
    company_name: 'Hauck Group',
    product_image: product2,
    reviewer: 'Nester Oliffe',
    email: 'noliffe1q@tinypic.com',
    avatar: avatar1,
    date: '3/31/2021',
    status: 'Published',
    review: 4,
    head: 'sagittis nam congue',
    para: 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
  },
  {
    id: 64,
    product: 'Rembucket',
    company_name: 'Reynolds-Lindgren',
    product_image: product2,
    reviewer: 'Cheryl Growcott',
    email: 'cgrowcott1r@nifty.com',
    avatar: avatar1,
    date: '10/29/2021',
    status: 'Pending',
    review: 4,
    head: 'amet diam in magna bibendum',
    para: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
  },
  {
    id: 65,
    product: 'Tin',
    company_name: 'Stroman and Sons',
    product_image: product2,
    reviewer: 'Calhoun Perot',
    email: 'cperot1s@goodreads.com',
    avatar: avatar1,
    date: '10/15/2020',
    status: 'Published',
    review: 4,
    head: 'enim blandit mi',
    para: 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
  },
  {
    id: 66,
    product: 'Trippledex',
    company_name: 'Kihn-Wisoky',
    product_image: product2,
    reviewer: 'Winnah Tivenan',
    email: 'wtivenan1t@example.com',
    avatar: avatar1,
    date: '5/27/2021',
    status: 'Published',
    review: 3,
    head: 'pede ullamcorper augue a suscipit',
    para: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
  },
  {
    id: 67,
    product: 'Redhold',
    company_name: 'Konopelski-Hauck',
    product_image: product2,
    reviewer: 'Faydra Perceval',
    email: 'fperceval1u@psu.edu',
    avatar: avatar1,
    date: '10/2/2020',
    status: 'Published',
    review: 2,
    head: 'porta volutpat',
    para: 'In congue. Etiam justo. Etiam pretium iaculis justo.',
  },
  {
    id: 68,
    product: 'Pannier',
    company_name: 'Rau Inc',
    product_image: product3,
    reviewer: 'Shauna Runge',
    email: 'srunge1v@theatlantic.com',
    avatar: avatar1,
    date: '12/17/2021',
    status: 'Published',
    review: 3,
    head: 'aliquam lacus morbi quis tortor',
    para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
  },
  {
    id: 69,
    product: 'Rlexidy',
    company_name: 'Torp-Lebsack',
    product_image: product3,
    reviewer: 'Udell Laurand',
    email: 'ulaurand1w@prnewswire.com',
    avatar: avatar1,
    date: '3/14/2021',
    status: 'Pending',
    review: 5,
    head: 'vestibulum velit id pretium',
    para: 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
  },
  {
    id: 70,
    product: 'Keylex',
    company_name: 'Hane-Bednar',
    product_image: product3,
    reviewer: 'Charyl Mordaunt',
    email: 'cmordaunt1x@bizjournals.com',
    avatar: avatar1,
    date: '4/11/2021',
    status: 'Pending',
    review: 1,
    head: 'amet eros suspendisse accumsan tortor',
    para: 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
  },
  {
    id: 71,
    product: 'Kuobam',
    company_name: 'Rice Group',
    product_image: product3,
    reviewer: 'Becki Petit',
    email: 'bpetit1y@addtoany.com',
    avatar: avatar1,
    date: '8/9/2021',
    status: 'Published',
    review: 5,
    head: 'blandit lacinia erat vestibulum sed',
    para: 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
  },
  {
    id: 72,
    product: 'Ulphazap',
    company_name: 'West, White and Rau',
    product_image: product3,
    reviewer: 'Gallagher Goldes',
    email: 'ggoldes1z@microsoft.com',
    avatar: avatar1,
    date: '10/21/2020',
    status: 'Pending',
    review: 4,
    head: 'vitae ipsum aliquam',
    para: 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
  },
  {
    id: 73,
    product: 'Wiodex',
    company_name: 'Keeling-Dicki',
    product_image: product4,
    reviewer: 'Gunilla Painter',
    email: 'gpainter20@drupal.org',
    avatar: avatar1,
    date: '12/11/2021',
    status: 'Published',
    review: 4,
    head: 'tortor duis mattis egestas',
    para: 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
  },
  {
    id: 74,
    product: 'Veribet',
    company_name: 'Gerlach, Bernier and Jenkins',
    product_image: product4,
    reviewer: 'Greggory Illingworth',
    email: 'gillingworth21@lis',
    avatar: avatar1,
    date: '8/8/2020',
    status: 'Pending',
    review: 4,
    head: 'pede justo lacinia eget tincidunt',
    para: 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
  },
  {
    id: 75,
    product: 'Rix San',
    company_name: 'Kessler and Sons',
    product_image: product4,
    reviewer: 'Amabel Reah',
    email: 'areah22@indiegogo.com',
    avatar: avatar1,
    date: '11/22/2021',
    status: 'Published',
    review: 3,
    head: 'sit amet lobortis sapien',
    para: 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
  },
  {
    id: 76,
    product: 'Zoolab',
    company_name: 'Goldner, Lind and Hansen',
    product_image: product4,
    reviewer: 'Eziechiele Littlejohns',
    email: 'elittlejohns23@blogger.com',
    avatar: avatar1,
    date: '8/17/2020',
    status: 'Pending',
    review: 4,
    head: 'cras non velit',
    para: 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
  },
  {
    id: 77,
    product: 'Rob',
    company_name: 'Trantow Group',
    product_image: product4,
    reviewer: 'Faythe Hance',
    email: 'fhance24@odnoklassniki.ru',
    avatar: avatar1,
    date: '7/1/2021',
    status: 'Published',
    review: 5,
    head: 'luctus tincidunt nulla mollis molestie',
    para: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
  },
  {
    id: 78,
    product: 'Zamit',
    company_name: 'Reichel, Hagenes and Nader',
    product_image: product5,
    reviewer: 'Marie Hazelton',
    email: 'mhazelton25@miitbeian.gov.cn',
    avatar: avatar1,
    date: '5/31/2021',
    status: 'Published',
    review: 1,
    head: 'ut odio cras',
    para: 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
  },
  {
    id: 79,
    product: 'Zoolab',
    company_name: 'Baumbach-Renner',
    product_image: product5,
    reviewer: 'Vincenz Izsak',
    email: 'vizsak26@diigo.com',
    avatar: avatar1,
    date: '3/15/2021',
    status: 'Pending',
    review: 2,
    head: 'gravida sem',
    para: 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
  },
  {
    id: 80,
    product: 'Stronghold',
    company_name: 'Ullrich, Jacobson and Tillman',
    product_image: product5,
    reviewer: 'Roch Dehmel',
    email: 'rdehmel27@tiny.cc',
    avatar: avatar1,
    date: '4/21/2020',
    status: 'Pending',
    review: 3,
    head: 'ligula pellentesque ultrices phasellus',
    para: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
  },
  {
    id: 81,
    product: 'Rintone',
    company_name: 'VonRueden, Kuphal and Lindgren',
    product_image: product5,
    reviewer: 'Marylin Thewlis',
    email: 'mthewlis28@tmall.com',
    avatar: avatar1,
    date: '5/26/2021',
    status: 'Pending',
    review: 1,
    head: 'elementum nullam varius nulla',
    para: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
  },
  {
    id: 82,
    product: 'Temp',
    company_name: 'Wintheiser, Bergstrom and Schimmel',
    product_image: product5,
    reviewer: 'Annissa Mapham',
    email: 'amapham29@cbslocal.com',
    avatar: avatar1,
    date: '6/10/2021',
    status: 'Published',
    review: 4,
    head: 'odio porttitor',
    para: 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
  },
  {
    id: 83,
    product: 'Rlexidy',
    company_name: 'Kuhn and Sons',
    product_image: product6,
    reviewer: 'Lori Prosek',
    email: 'lprosek2a@webs.com',
    avatar: avatar1,
    date: '7/16/2021',
    status: 'Published',
    review: 1,
    head: 'lacinia sapien quis',
    para: 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
  },
  {
    id: 84,
    product: 'Ronstring',
    company_name: 'Goldner, Nitzsche and Rau',
    product_image: product6,
    reviewer: 'Zelma Jado',
    email: 'zjado2b@salon.com',
    avatar: avatar1,
    date: '7/13/2021',
    status: 'Pending',
    review: 4,
    head: 'mauris sit amet eros suspendisse',
    para: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
  },
  {
    id: 85,
    product: 'Rixflex',
    company_name: 'Bayer-Beer',
    product_image: product6,
    reviewer: 'Alfreda Tuffley',
    email: 'atuffley2c@drupal.org',
    avatar: avatar1,
    date: '3/25/2020',
    status: 'Pending',
    review: 2,
    head: 'molestie hendrerit at vulputate vitae',
    para: 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
  },
  {
    id: 86,
    product: 'Uerified',
    company_name: 'Rolfson-Witting',
    product_image: product6,
    reviewer: 'Arnold Rate',
    email: 'arate2d@mit.edu',
    avatar: avatar1,
    date: '7/22/2021',
    status: 'Pending',
    review: 1,
    head: 'nisi venenatis tristique fusce',
    para: 'Phasellus in felis. Donec semper sapien a libero. Nam dui.',
  },
  {
    id: 87,
    product: 'Stringtough',
    company_name: 'Kunde-Gibson',
    product_image: product7,
    reviewer: 'Felizio Macieiczyk',
    email: 'fmacieiczyk2e@sciencedaily.com',
    avatar: avatar1,
    date: '8/27/2020',
    status: 'Published',
    review: 4,
    head: 'augue quam sollicitudin',
    para: 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
  },
  {
    id: 88,
    product: 'Qookley',
    company_name: 'Kshlerin-Klocko',
    product_image: product7,
    reviewer: 'Evanne Chamley',
    email: 'echamley2f@gmpg.org',
    avatar: avatar1,
    date: '2/1/2021',
    status: 'Pending',
    review: 4,
    head: 'eget tincidunt',
    para: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
  },
  {
    id: 89,
    product: 'Zamit',
    company_name: 'Reilly, Marvin and Ondricka',
    product_image: product7,
    reviewer: 'Dacy Goodlatt',
    email: 'dgoodlatt2g@squarespace.com',
    avatar: avatar1,
    date: '4/15/2021',
    status: 'Pending',
    review: 4,
    head: 'eu interdum eu',
    para: 'In congue. Etiam justo. Etiam pretium iaculis justo.',
  },
  {
    id: 90,
    product: 'Mat Lam Tam',
    company_name: 'Ratke-Bauch',
    product_image: product7,
    reviewer: 'Samantha Vickerman',
    email: 'svickerman2h@earthlink.net',
    avatar: avatar1,
    date: '6/30/2021',
    status: 'Pending',
    review: 3,
    head: 'leo rhoncus sed vestibulum',
    para: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
  },
  {
    id: 91,
    product: 'Rt',
    company_name: 'Kautzer-Hayes',
    product_image: product8,
    reviewer: 'Maura Robichon',
    email: 'mrobichon2i@accuweather.com',
    avatar: avatar1,
    date: '4/12/2020',
    status: 'Published',
    review: 3,
    head: 'dui maecenas',
    para: 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
  },
  {
    id: 92,
    product: 'Stim',
    company_name: 'Bernhard and Sons',
    product_image: product8,
    reviewer: 'Shelton Bonde',
    email: 'sbonde2j@economist.com',
    avatar: avatar1,
    date: '6/1/2021',
    status: 'Pending',
    review: 1,
    head: 'odio elementum',
    para: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
  },
  {
    id: 93,
    product: 'Rix San',
    company_name: 'Waters, Harvey and Stiedemann',
    product_image: product8,
    reviewer: 'Hallsy Flannigan',
    email: 'hflannigan2k@printfriendly.com',
    avatar: avatar1,
    date: '6/3/2020',
    status: 'Published',
    review: 5,
    head: 'ultrices phasellus id',
    para: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
  },
  {
    id: 94,
    product: 'Vagram',
    company_name: 'Ondricka, Thompson and Kuhn',
    product_image: product8,
    reviewer: 'Rheta Chazelas',
    email: 'rchazelas2l@forbes.com',
    avatar: avatar1,
    date: '2/21/2021',
    status: 'Pending',
    review: 1,
    head: 'eleifend quam',
    para: 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
  },
  {
    id: 95,
    product: 'Otcom',
    company_name: 'Volkman Group',
    product_image: product9,
    reviewer: 'Arabelle Uc',
    email: 'auc2m@archive.org',
    avatar: avatar1,
    date: '1/27/2021',
    status: 'Published',
    review: 4,
    head: 'fermentum justo',
    para: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
  },
  {
    id: 96,
    product: 'Rixflex',
    company_name: 'Dickinson, Spencer and Hyatt',
    product_image: product9,
    reviewer: 'Pauly Goulden',
    email: 'pgoulden2n@ed.gov',
    avatar: avatar1,
    date: '10/2/2020',
    status: 'Pending',
    review: 2,
    head: 'morbi ut',
    para: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',
  },
  {
    id: 97,
    product: 'Lotstring',
    company_name: 'Marvin Inc',
    product_image: product9,
    reviewer: 'Wilhelmina Benezet',
    email: 'wbenezet2o@themeforest.net',
    avatar: avatar1,
    date: '8/12/2021',
    status: 'Pending',
    review: 4,
    head: 'sapien cursus vestibulum proin',
    para: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
  },
  {
    id: 98,
    product: 'Wiodex',
    company_name: 'Hayes-Greenholt',
    product_image: product9,
    reviewer: 'Wallie Paolone',
    email: 'wpaolone2p@paginegialle.it',
    avatar: avatar1,
    date: '7/15/2021',
    status: 'Published',
    review: 2,
    head: 'tincidunt in leo maecenas',
    para: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
  },
  {
    id: 99,
    product: 'Komainer',
    company_name: 'Gislason, Greenfelder and Wisozk',
    product_image: product10,
    reviewer: 'Ezmeralda Normavill',
    email: 'enormavill2q@infoseek.co.jp',
    avatar: avatar1,
    date: '8/4/2021',
    status: 'Pending',
    review: 3,
    head: 'pharetra magna ac',
    para: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
  },
  {
    id: 100,
    product: 'Ulpha',
    company_name: 'Kunde Group',
    product_image: product10,
    reviewer: 'Lew Dudman',
    email: 'ldudman2r@nationalgeographic.com',
    avatar: avatar1,
    date: '11/12/2020',
    status: 'Published',
    review: 3,
    head: 'suscipit ligula in lacus',
    para: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
  },
]

const referrals = [

  {
    id: 1,
    user: 'Koressa Leyfield',
    email: 'kleyfield0@columbia.edu',
    avatar: avatar1,
    referred_id: 3398,
    status: 2,
    value: '$6655.92',
    earning: '$380.17',
  },
  {
    id: 2,
    user: 'Tania Brotherhood',
    email: 'tbrotherhood1@bing.com',
    avatar: avatar13,
    referred_id: 6740,
    status: 2,
    value: '$2113.04',
    earning: '$716.72',
  },
  {
    id: 3,
    user: 'Clemmie Montgomery',
    email: 'cmontgomery2@fema.gov',
    avatar: avatar1,
    referred_id: 2749,
    status: 2,
    value: '$6717.09',
    earning: '$699.02',
  },
  {
    id: 4,
    user: 'Job Jope',
    email: 'jjope3@istockphoto.com',
    avatar: avatar15,
    referred_id: 1413,
    status: 3,
    value: '$9465.13',
    earning: '$98.23',
  },
  {
    id: 5,
    user: 'Christoffer Derell',
    email: 'cderell4@apple.com',
    avatar: avatar1,
    referred_id: 9176,
    status: 3,
    value: '$6202.81',
    earning: '$882.51',
  },
  {
    id: 6,
    user: 'Herminia Eyree',
    email: 'heyree5@gizmodo.com',
    avatar: avatar8,
    referred_id: 6975,
    status: 2,
    value: '$9802.40',
    earning: '$219.52',
  },
  {
    id: 7,
    user: 'Dela Lathwell',
    email: 'dlathwell6@webmd.com',
    avatar: avatar9,
    referred_id: 4552,
    status: 3,
    value: '$6470.46',
    earning: '$831.45',
  },
  {
    id: 8,
    user: 'Kirbie Greenhow',
    email: 'kgreenhow7@sina.com.cn',
    avatar: avatar1,
    referred_id: 4131,
    status: 2,
    value: '$6199.28',
    earning: '$856.00',
  },
  {
    id: 9,
    user: 'Adrienne Tourne',
    email: 'atourne8@fotki.com',
    avatar: avatar1,
    referred_id: 4072,
    status: 2,
    value: '$6774.33',
    earning: '$821.78',
  },
  {
    id: 10,
    user: 'Vanya Hearons',
    email: 'vhearons9@blogspot.com',
    avatar: avatar9,
    referred_id: 3070,
    status: 2,
    value: '$1067.14',
    earning: '$804.91',
  },
  {
    id: 11,
    user: 'Garnette Abramcik',
    email: 'gabramcika@google.com',
    avatar: avatar11,
    referred_id: 7828,
    status: 2,
    value: '$5375.10',
    earning: '$447.01',
  },
  {
    id: 12,
    user: 'Akim Korba',
    email: 'akorbab@flickr.com',
    avatar: avatar11,
    referred_id: 8561,
    status: 2,
    value: '$3104.91',
    earning: '$552.75',
  },
  {
    id: 13,
    user: 'Cull Scipsey',
    email: 'cscipseyc@adobe.com',
    avatar: avatar2,
    referred_id: 9287,
    status: 3,
    value: '$9375.13',
    earning: '$690.75',
  },
  {
    id: 14,
    user: 'Anabal Hakking',
    email: 'ahakkingd@paginegialle.it',
    avatar: avatar7,
    referred_id: 4892,
    status: 3,
    value: '$8797.12',
    earning: '$679.71',
  },
  {
    id: 15,
    user: 'Linzy Swiers',
    email: 'lswierse@flickr.com',
    avatar: avatar5,
    referred_id: 9180,
    status: 2,
    value: '$2996.63',
    earning: '$610.27',
  },
  {
    id: 16,
    user: 'Willy Espinet',
    email: 'wespinetf@addtoany.com',
    avatar: avatar1,
    referred_id: 9102,
    status: 3,
    value: '$7048.18',
    earning: '$369.06',
  },
  {
    id: 17,
    user: 'Carter Gommowe',
    email: 'cgommoweg@purevolume.com',
    avatar: avatar9,
    referred_id: 7049,
    status: 2,
    value: '$6049.95',
    earning: '$642.78',
  },
  {
    id: 18,
    user: 'Andre Kenway',
    email: 'akenwayh@rambler.ru',
    avatar: avatar6,
    referred_id: 9826,
    status: 3,
    value: '$2221.71',
    earning: '$347.19',
  },
  {
    id: 19,
    user: 'Quintina Endacott',
    email: 'qendacotti@answers.com',
    avatar: avatar9,
    referred_id: 4555,
    status: 3,
    value: '$5918.70',
    earning: '$543.44',
  },
  {
    id: 20,
    user: 'Shurwood Cabble',
    email: 'scabblej@twitpic.com',
    avatar: avatar4,
    referred_id: 5591,
    status: 3,
    value: '$9073.50',
    earning: '$980.62',
  },
  {
    id: 21,
    user: 'Thatch Borchardt',
    email: 'tborchardtk@bing.com',
    avatar: avatar1,
    referred_id: 4491,
    status: 2,
    value: '$8389.56',
    earning: '$746.81',
  },
  {
    id: 22,
    user: 'Fawne O\'Scanlan',
    email: 'foscanlanl@europa.eu',
    avatar: avatar8,
    referred_id: 2946,
    status: 3,
    value: '$7471.34',
    earning: '$747.24',
  },
  {
    id: 23,
    user: 'Ode Birts',
    email: 'obirtsm@sphinn.com',
    avatar: avatar10,
    referred_id: 2328,
    status: 3,
    value: '$8484.83',
    earning: '$815.79',
  },
  {
    id: 24,
    user: 'Bella Michelle',
    email: 'bmichellen@npr.org',
    avatar: avatar2,
    referred_id: 5725,
    status: 3,
    value: '$7088.56',
    earning: '$329.64',
  },
  {
    id: 25,
    user: 'Aurora Skpsey',
    email: 'askpseyo@cdc.gov',
    avatar: avatar14,
    referred_id: 2821,
    status: 2,
    value: '$2938.87',
    earning: '$317.42',
  },
  {
    id: 26,
    user: 'Neddie Maunders',
    email: 'nmaundersp@blogspot.com',
    avatar: avatar15,
    referred_id: 1661,
    status: 2,
    value: '$6256.70',
    earning: '$521.01',
  },
  {
    id: 27,
    user: 'Andria Chisnell',
    email: 'achisnellq@imageshack.us',
    avatar: avatar12,
    referred_id: 3363,
    status: 2,
    value: '$9106.99',
    earning: '$705.15',
  },
  {
    id: 28,
    user: 'Reggy Arnao',
    email: 'rarnaor@kickstarter.com',
    avatar: avatar3,
    referred_id: 7814,
    status: 1,
    value: '$6300.60',
    earning: '$234.28',
  },
  {
    id: 29,
    user: 'Shaylah Hasselby',
    email: 'shasselbys@odnoklassniki.ru',
    avatar: avatar4,
    referred_id: 8324,
    status: 3,
    value: '$1874.21',
    earning: '$899.72',
  },
  {
    id: 30,
    user: 'Althea Dayce',
    email: 'adaycet@youtu.be',
    avatar: avatar8,
    referred_id: 6069,
    status: 3,
    value: '$6098.09',
    earning: '$269.32',
  },
  {
    id: 31,
    user: 'Hector Biaggioli',
    email: 'hbiaggioliu@umich.edu',
    avatar: avatar13,
    referred_id: 5286,
    status: 3,
    value: '$4752.66',
    earning: '$546.63',
  },
  {
    id: 32,
    user: 'Mycah Gotcher',
    email: 'mgotcherv@yellowbook.com',
    avatar: avatar1,
    referred_id: 7944,
    status: 2,
    value: '$5959.05',
    earning: '$888.10',
  },
  {
    id: 33,
    user: 'Garv Scruton',
    email: 'gscrutonw@sun.com',
    avatar: avatar13,
    referred_id: 6876,
    status: 2,
    value: '$6588.37',
    earning: '$680.51',
  },
  {
    id: 34,
    user: 'Renell Gurnett',
    email: 'rgurnettx@businessweek.com',
    avatar: avatar2,
    referred_id: 7802,
    status: 1,
    value: '$7542.30',
    earning: '$208.96',
  },
  {
    id: 35,
    user: 'Toinette Kilgrew',
    email: 'tkilgrewy@wikispaces.com',
    avatar: avatar15,
    referred_id: 6946,
    status: 3,
    value: '$4447.48',
    earning: '$410.48',
  },
  {
    id: 36,
    user: 'Corinne Cockshtt',
    email: 'ccockshttz@house.gov',
    avatar: avatar7,
    referred_id: 1372,
    status: 3,
    value: '$3700.16',
    earning: '$858.94',
  },
  {
    id: 37,
    user: 'Isis Yurkiewicz',
    email: 'iyurkiewicz10@addthis.com',
    avatar: avatar4,
    referred_id: 2384,
    status: 2,
    value: '$7456.86',
    earning: '$280.52',
  },
  {
    id: 38,
    user: 'Gerianna Nott',
    email: 'gnott11@youtu.be',
    avatar: avatar5,
    referred_id: 1971,
    status: 3,
    value: '$5563.94',
    earning: '$515.34',
  },
  {
    id: 39,
    user: 'Calli Mewes',
    email: 'cmewes12@mit.edu',
    avatar: avatar13,
    referred_id: 7323,
    status: 2,
    value: '$7400.29',
    earning: '$167.44',
  },
  {
    id: 40,
    user: 'Sonnnie Keeltagh',
    email: 'skeeltagh13@typepad.com',
    avatar: avatar7,
    referred_id: 5719,
    status: 3,
    value: '$1977.34',
    earning: '$652.01',
  },
  {
    id: 41,
    user: 'Penelope Hause',
    email: 'phause14@netlog.com',
    avatar: avatar3,
    referred_id: 9347,
    status: 3,
    value: '$2155.12',
    earning: '$101.49',
  },
  {
    id: 42,
    user: 'Dannie Romeo',
    email: 'dromeo15@ask.com',
    avatar: avatar1,
    referred_id: 1559,
    status: 1,
    value: '$7110.30',
    earning: '$95.40',
  },
  {
    id: 43,
    user: 'Keely Giannazzi',
    email: 'kgiannazzi16@mit.edu',
    avatar: avatar8,
    referred_id: 3307,
    status: 3,
    value: '$2178.00',
    earning: '$173.10',
  },
  {
    id: 44,
    user: 'Kassia Mottini',
    email: 'kmottini17@usa.gov',
    avatar: avatar7,
    referred_id: 4426,
    status: 1,
    value: '$6921.60',
    earning: '$365.93',
  },
  {
    id: 45,
    user: 'Burr Scrauniage',
    email: 'bscrauniage18@wunderground.com',
    avatar: avatar8,
    referred_id: 3570,
    status: 3,
    value: '$6891.09',
    earning: '$900.25',
  },

]

// eslint-disable-next-line sonarjs/cognitive-complexity
mock.onGet('/apps/ecommerce/products/list').reply(config => {
  const { q = '', stock = undefined, category = null, status = null, options = {} } = config.params ?? {}

  const { sortBy = '', itemsPerPage = 10, page = 1 } = options

  const sort = JSON.parse(JSON.stringify(sortBy))

  console.log(sort)

  const queryLower = q.toLowerCase()

  console.log(category, status, stock)

  console.log('Filetered by stock', products.filter(product =>
    product.stock === (stock || product.stock),
  ))

  // Filtering Products
  let filteredProducts = products.filter(product => (
    (product.product_name.toLowerCase().includes(queryLower) || product.product_brand.toLowerCase().includes(queryLower))
    && product.category === (category || product.category) && product.status === (status || product.status) && product.stock === (stock || product.stock)
  )).reverse()

  // Sort
  if (sort.length) {
    if (sort[0].key === 'product') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.product_name.toLowerCase() > b.product_name.toLowerCase() ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.product_name.toLowerCase() < b.product_name.toLowerCase() ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'category') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.category > b.category ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.category < b.category ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'status') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.status > b.status ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.status < b.status ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'price') {
      filteredProducts = filteredProducts.sort((a, b) => {
        console.log(a.price.slice(1))
        if (sort[0].order === 'asc')
          return Number(a.price.slice(1)) > Number(b.price.slice(1)) ? 1 : -1
        else if (sort[0].order === 'desc')
          return Number(a.price.slice(1)) < Number(b.price.slice(1)) ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'qty') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.qty > b.qty ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.qty < b.qty ? 1 : -1

        return 0
      })
    }

    if (sort[0].key === 'sku') {
      filteredProducts = filteredProducts.sort((a, b) => {
        if (sort[0].order === 'asc')
          return a.sku > b.sku ? 1 : -1
        else if (sort[0].order === 'desc')
          return a.sku < b.sku ? 1 : -1

        return 0
      })
    }
  }
  console.log(filteredProducts)

  return [200, { products: paginateArray(filteredProducts, itemsPerPage, page), total: filteredProducts.length }]
})

mock.onGet('/apps/ecommerce/reviews/list').reply(config => {
  const { q = '', options = {} } = config.params ?? {}

  const { sortBy = '', itemsPerPage = 10, page = 1 } = options

  const sort = JSON.parse(JSON.stringify(sortBy))

  const queryLower = q.toLowerCase()

  // Filtering Reviews

  const filteredReviews = reviews.filter(review => {
    const { product, reviewer, email } = review

    return (
      (product.toLowerCase().includes(queryLower) || reviewer.toLowerCase().includes(queryLower) || email.toLowerCase().includes(queryLower) || review.head.toLowerCase().includes(queryLower) || review.para.toLowerCase().includes(queryLower))
    )
  })

  // Sort
  if (sort.length) {
    if (sort[0]?.key === 'product') {
      filteredReviews.sort((a, b) => {
        if (sort[0]?.order === 'asc')
          return a.product.toLowerCase() > b.product.toLowerCase() ? 1 : -1
        else if (sort[0]?.order === 'desc')
          return a.product.toLowerCase() < b.product.toLowerCase() ? 1 : -1

        return 0
      })
    }

    if (sort[0]?.key === 'reviewer') {
      filteredReviews.sort((a, b) => {
        if (sort[0]?.order === 'asc')
          return a.reviewer.toLowerCase() > b.reviewer.toLowerCase() ? 1 : -1
        else if (sort[0]?.order === 'desc')
          return a.reviewer.toLowerCase() < b.reviewer.toLowerCase() ? 1 : -1

        return 0
      })
    }

    if (sort[0]?.key === 'date') {
      filteredReviews.sort((a, b) => {
        if (sort[0]?.order === 'desc')
          return Number(new Date(b.date)) - Number(new Date(a.date))
        else if (sort[0]?.order === 'asc')
          return Number(new Date(a.date)) - Number(new Date(b.date))

        return 0
      })
    }
  }

  return [200, { reviews: paginateArray(filteredReviews, itemsPerPage, page), total: reviews.length }]
})

mock.onGet('/apps/ecommerce/referrals').reply(config => {
  const { options = {} } = config.params ?? {}

  const { sortBy = '', itemsPerPage = 10, page = 1 } = options

  const sort = JSON.parse(JSON.stringify(sortBy))

  console.log(sort)

  const filteredReferrals = referrals
  if (sort.length) {
    console.log('inside sort', filteredReferrals)
    if (sort[0]?.key === 'users') {
      filteredReferrals.sort((a, b) => {
        if (sort[0]?.order === 'asc')
          return a.user.toLowerCase() > b.user.toLowerCase() ? 1 : -1
        else if (sort[0]?.order === 'desc')
          return a.user.toLowerCase() < b.user.toLowerCase() ? 1 : -1

        return 0
      })
    }

    if (sort[0]?.key === 'referred-id') {
      filteredReferrals.sort((a, b) => {
        if (sort[0]?.order === 'asc')
          return a.referred_id - b.referred_id
        else if (sort[0]?.order === 'desc')
          return b.referred_id - a.referred_id

        return 0
      })
    }

    if (sort[0]?.key === 'earning') {
      filteredReferrals.sort((a, b) => {
        if (sort[0]?.order === 'asc')
          return Number(a.earning.slice(1)) - Number(b.earning.slice(1))
        else if (sort[0]?.order === 'desc')
          return Number(b.earning.slice(1)) - Number(a.earning.slice(1))

        return 0
      })
    }
  }
  console.log(filteredReferrals)

  return [200, { referrals: paginateArray(filteredReferrals, itemsPerPage, page), total: referrals.length }]
})

mock.onDelete(/\/apps\/ecommerce\/reviews\/\d+/).reply(config => {
  const id = Number(config.url?.substring(config.url?.lastIndexOf('/') + 1))

  console.log(id)

  const index = reviews.findIndex(review => review.id === id)

  if (index > -1) {
    reviews.splice(index, 1)

    return [200]
  }

  return [400]
})
