export const exPanelDefault = ''
export const exPanelAccordion = ''
export const exPanelFocusable = ''
export const exPanelInset = ''
export const exPanelModel = ''
export const exPanelPopout = ''
export const exPanelIcon = ''
