name: Deploy - Changelog

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checkout
      - uses: actions/checkout@v2
      - name: (production) Backup old Changelog file and remove old Backup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.PROJECTDIR }}
            rm -rf changelog-bak-*.zip
            CHANGELOG_ZIP_NAME="changelog-bak-$(date +"%Y-%m-%d-%H-%M-%S").zip"
            zip -r $CHANGELOG_ZIP_NAME changelog.html
            rm -rf changelog.html
      - name: Convert CHANGELOG.md to changelog.html
        uses: jd-solanki/gh-action-md-to-html@v1.1.0
        with:
          files: '[["CHANGELOG.md","./changelog.html"]]'
          theme: light
      - name: Upload CHANGELOG via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: changelog.html
          target: ${{ secrets.PROJECTDIR }}
